const weapons = [
  { "name": "わかばシューター", "name_en": "Splattershot Jr.", "class": "シューター", "sub": "スプラッシュボム", "sp": "グレートバリア", "range": 1, "imageId": "Wst_Splattershot_Jr._", "collection": "スプラシューター" },
  { "name": "オーダーシューターレプリカ", "name_en": "Order Shot Replica", "class": "シューター", "sub": "キューバンボム", "sp": "ウルトラショット", "range": 2, "imageId": "Wst_Order_Shot_Replica", "collection": "スプラシューター" },
  { "name": "オクタシューターレプリカ", "name_en": "Octoshot Replica", "class": "シューター", "sub": "スプラッシュボム", "sp": "トリプルトルネード", "range": 2, "imageId": "Wst_Octoshot_Replica", "collection": "スプラシューター" },
  { "name": "ヒーローシューターレプリカ", "name_en": "Hero Shot Replica", "class": "シューター", "sub": "キューバンボム", "sp": "ウルトラショット", "range": 2, "imageId": "Wst_Hero_Shot_Replica", "collection": "スプラシューター" },
  { "name": "スプラシューター", "name_en": "Splattershot", "class": "シューター", "sub": "キューバンボム", "sp": "ウルトラショット", "range": 2, "imageId": "Wst_Splattershot", "collection": "スプラシューター" },
  { "name": "プロモデラーMG", "name_en": "Aerospray MG", "class": "シューター", "sub": "タンサンボム", "sp": "サメライド", "range": 1, "imageId": "Wst_Aerospray_MG", "collection": "プロモデラー" },
  { "name": "N-ZAP85", "name_en": "N-ZAP '85", "class": "シューター", "sub": "キューバンボム", "sp": "エナジースタンド", "range": 2, "imageId": "Wst_N-ZAP_85", "collection": "N-ZAP" },
  { "name": "もみじシューター", "name_en": "Custom Splattershot Jr.", "class": "シューター", "sub": "トーピード", "sp": "ホップソナー", "range": 1, "imageId": "Wst_Custom_Splattershot_Jr.", "collection": "スプラシューター" },
  { "name": "スペースシューター", "name_en": "Splattershot Nova", "class": "シューター", "sub": "ポイントセンサー", "sp": "メガホンレーザー5.1ch", "range": 3, "imageId": "Wst_Splattershot_Nova", "collection": "スペースシューター" },
  { "name": "ボールドマーカー", "name_en": "Sploosh-o-matic", "class": "シューター", "sub": "カーリングボム", "sp": "ウルトラハンコ", "range": 1, "imageId": "Wst_Sploosh-o-matic", "collection": "ボールドマーカー" },
  { "name": "プライムシューター", "name_en": "Splattershot Pro", "class": "シューター", "sub": "ラインマーカー", "sp": "カニタンク", "range": 3, "imageId": "Wst_Splattershot_Pro", "collection": "プライムシューター" },
  { "name": "スプラシューターコラボ", "name_en": "Tentatek Splattershot", "class": "シューター", "sub": "スプラッシュボム", "sp": "トリプルトルネード", "range": 2, "imageId": "Wst_Tentatek_Splattershot", "collection": "スプラシューター" },
  { "name": "N-ZAP89", "name_en": "N-ZAP '89", "class": "シューター", "sub": "ロボットボム", "sp": "デコイチラシ", "range": 2, "imageId": "Wst_N-ZAP_89", "collection": "N-ZAP" },
  { "name": "52ガロン", "name_en": ".52 Gal", "class": "シューター", "sub": "スプラッシュシールド", "sp": "メガホンレーザー5.1ch", "range": 2, "imageId": "Wst_52_Gal", "collection": ".52ガロン" },
  { "name": "スペースシューターコラボ", "name_en": "Annaki Splattershot Nova", "class": "シューター", "sub": "トラップ", "sp": "ジェットパック", "range": 3, "imageId": "Wst_Annaki_Splattershot_Nova", "collection": "スペースシューター" },
  { "name": "スプラシューター煌", "name_en": "Kensa Splattershot", "class": "シューター", "sub": "クイックボム", "sp": "テイオウイカ", "range": 2, "imageId": "Wst_Kensa_Splattershot", "collection": "スプラシューター" },
  { "name": "ボールドマーカーネオ", "name_en": "Neo Sploosh-o-matic", "class": "シューター", "sub": "ジャンプビーコン", "sp": "メガホンレーザー5.1ch", "range": 1, "imageId": "Wst_Neo_Sploosh-o-matic", "collection": "ボールドマーカー" },
  { "name": "L3リールガン", "name_en": "L-3 Nozzlenose", "class": "シューター", "sub": "カーリングボム", "sp": "カニタンク", "range": 3, "imageId": "Wst_L-3_Nozzlenose", "collection": "L3リールガン" },
  { "name": "52ガロンデコ", "name_en": ".52 Gal Deco", "class": "シューター", "sub": "カーリングボム", "sp": "スミナガシート", "range": 2, "imageId": "Wst_52_Gal_Deco", "collection": ".52ガロン" },
  { "name": "ジェットスイーパー", "name_en": "Jet Squelcher", "class": "シューター", "sub": "ラインマーカー", "sp": "キューインキ", "range": 5, "imageId": "Wst_Jet_Squelcher", "collection": "ジェットスイーパー" },
  { "name": "シャープマーカー", "name_en": "Splash-o-matic", "class": "シューター", "sub": "クイックボム", "sp": "カニタンク", "range": 2, "imageId": "Wst_Splash-o-matic", "collection": "シャープマーカー" },
  { "name": "96ガロン", "name_en": ".96 Gal", "class": "シューター", "sub": "スプリンクラー", "sp": "キューインキ", "range": 3, "imageId": "Wst_96_Gal", "collection": ".96ガロン" },
  { "name": "プロモデラーRG", "name_en": "Aerospray RG", "class": "シューター", "sub": "スプリンクラー", "sp": "ナイスダマ", "range": 1, "imageId": "Wst_Aerospray_RG", "collection": "プロモデラー" },
  { "name": "L3リールガンD", "name_en": "L-3 Nozzlenose D", "class": "シューター", "sub": "クイックボム", "sp": "ウルトラハンコ", "range": 3, "imageId": "Wst_L-3_Nozzlenose_D", "collection": "L3リールガン" },
  { "name": "プロモデラー彩", "name_en": "Aerospray PG", "class": "シューター", "sub": "クイックボム", "sp": "スミナガシート", "range": 1, "imageId": "Wst_Aerospray_PG", "collection": "プロモデラー" },
  { "name": "ボトルガイザー", "name_en": "Squeezer", "class": "シューター", "sub": "スプラッシュシールド", "sp": "ウルトラショット", "range": 4, "imageId": "Wst_Squeezer", "collection": "ボトルガイザー" },
  { "name": "プライムシューターコラボ", "name_en": "Forge Splattershot Pro", "class": "シューター", "sub": "キューバンボム", "sp": "ナイスダマ", "range": 3, "imageId": "Wst_Forge_Splattershot_Pro", "collection": "プライムシューター" },
  { "name": "L3リールガン箔", "name_en": "Foil L-3 Nozzlenose", "class": "シューター", "sub": "スプラッシュボム", "sp": "ジェットパック", "range": 3, "imageId": "Wst_Foil_L-3_Nozzlenose", "collection": "L3リールガン" },
  { "name": "ジェットスイーパーカスタム", "name_en": "Custom Jet Squelcher", "class": "シューター", "sub": "ポイズンミスト", "sp": "アメフラシ", "range": 5, "imageId": "Wst_Custom_Jet_Squelcher", "collection": "ジェットスイーパー" },
  { "name": "ジェットスイーパーCOBR", "name_en": "Mint-Camo Jet Squelcher", "class": "シューター", "sub": "クイックボム", "sp": "ウルトラチャクチ", "range": 5, "imageId": "Wst_Mint-Camo_Jet_Squelcher", "collection": "ジェットスイーパー" },
  { "name": "シャープマーカーネオ", "name_en": "Neo Splash-o-matic", "class": "シューター", "sub": "キューバンボム", "sp": "トリプルトルネード", "range": 2, "imageId": "Wst_Neo_Splash-o-matic", "collection": "シャープマーカー" },
  { "name": "シャープマーカーGECK", "name_en": "Annaki Splash-o-matic", "class": "シューター", "sub": "ポイズンミスト", "sp": "マルチミサイル", "range": 2, "imageId": "Wst_Annaki_Splash-o-matic", "collection": "シャープマーカー" },
  { "name": "96ガロンデコ", "name_en": ".96 Gal Deco", "class": "シューター", "sub": "スプラッシュシールド", "sp": "テイオウイカ", "range": 3, "imageId": "Wst_96_Gal_Deco", "collection": ".96ガロン" },
  { "name": "プライムシューターFRZN", "name_en": "Kensa Splattershot Pro", "class": "シューター", "sub": "スプラッシュボム", "sp": "マルチミサイル", "range": 3, "imageId": "Wst_Kensa_Splattershot_Pro", "collection": "プライムシューター" },
  { "name": "H3リールガン", "name_en": "H-3 Nozzlenose", "class": "シューター", "sub": "ポイントセンサー", "sp": "エナジースタンド", "range": 4, "imageId": "Wst_H-3_Nozzlenose", "collection": "H3リールガン" },
  { "name": "96ガロン爪", "name_en": "Kensa .96 Gal", "class": "シューター", "sub": "ラインマーカー", "sp": "エナジースタンド", "range": 3, "imageId": "Wst_Kensa_96_Gal", "collection": ".96ガロン" },
  { "name": "ボトルガイザーフォイル", "name_en": "Foil Squeezer", "class": "シューター", "sub": "ロボットボム", "sp": "スミナガシート", "range": 4, "imageId": "Wst_Foil_Squeezer", "collection": "ボトルガイザー" },
  { "name": "H3リールガンD", "name_en": "H-3 Nozzlenose D", "class": "シューター", "sub": "スプラッシュシールド", "sp": "グレートバリア", "range": 4, "imageId": "Wst_H-3_Nozzlenose_D", "collection": "H3リールガン" },
  { "name": "H3リールガンSNAK", "name_en": "Annaki H-3 Nozzlenose", "class": "シューター", "sub": "キューバンボム", "sp": "トリプルトルネード", "range": 4, "imageId": "Wst_Annaki_H-3_Nozzlenose", "collection": "H3リールガン" },
  { "name": "オーダーチャージャーレプリカ", "name_en": "Order Charger Replica", "class": "チャージャー", "sub": "スプラッシュボム", "sp": "キューインキ", "range": 5, "imageId": "Wst_Order_Charger_Replica", "collection": "スプラチャージャー" },
  { "name": "スプラチャージャー", "name_en": "Splat Charger", "class": "チャージャー", "sub": "スプラッシュボム", "sp": "キューインキ", "range": 5, "imageId": "Wst_Splat_Charger", "collection": "スプラチャージャー" },
  { "name": "スクイックリンα", "name_en": "Classic Squiffer", "class": "チャージャー", "sub": "ポイントセンサー", "sp": "グレートバリア", "range": 3, "imageId": "Wst_Classic_Squiffer", "collection": "スクイックリン" },
  { "name": "スプラチャージャーコラボ", "name_en": "Z+F Splat Charger", "class": "チャージャー", "sub": "スプラッシュシールド", "sp": "トリプルトルネード", "range": 5, "imageId": "Wst_Z+F_Splat_Charger", "collection": "スプラチャージャー" },
  { "name": "スプラスコープ", "name_en": "Splatterscope", "class": "チャージャー", "sub": "スプラッシュボム", "sp": "キューインキ", "range": 5, "imageId": "Wst_Splatterscope", "collection": "スプラチャージャー" },
  { "name": "スプラチャージャーFRST", "name_en": "Kensa Charger", "class": "チャージャー", "sub": "スプリンクラー", "sp": "カニタンク", "range": 5, "imageId": "Wst_Kensa_Charger", "collection": "スプラチャージャー" },
  { "name": "スクイックリンβ", "name_en": "New Squiffer", "class": "チャージャー", "sub": "ロボットボム", "sp": "ショクワンダー", "range": 3, "imageId": "Wst_New_Squiffer", "collection": "スクイックリン" },
  { "name": "R-PEN/5H", "name_en": "Bamboozler 14 Mk I", "class": "チャージャー", "sub": "スプリンクラー", "sp": "エナジースタンド", "range": 4, "imageId": "Wst_Bamboozler_14_Mk_I", "collection": "14式竹筒銃" },
  { "name": "スプラスコープコラボ", "name_en": "Z+F Splatterscope", "class": "チャージャー", "sub": "スプラッシュシールド", "sp": "トリプルトルネード", "range": 5, "imageId": "Wst_Z+F_Splatterscope", "collection": "スプラチャージャー" },
  { "name": "スプラスコープFRST", "name_en": "Kensa Splatterscope", "class": "チャージャー", "sub": "スプリンクラー", "sp": "カニタンク", "range": 5, "imageId": "Wst_Kensa_Splatterscope", "collection": "スプラチャージャー" },
  { "name": "リッター4K", "name_en": "E-liter 4K", "class": "チャージャー", "sub": "トラップ", "sp": "ホップソナー", "range": 5, "imageId": "Wst_E-liter_4K", "collection": "リッター4K" },
  { "name": "R-PEN/5B", "name_en": "Bamboozler 14 Mk II", "class": "チャージャー", "sub": "スプラッシュシールド", "sp": "アメフラシ", "range": 4, "imageId": "Wst_Bamboozler_14_Mk_II", "collection": "14式竹筒銃" },
  { "name": "リッター4Kカスタム", "name_en": "Custom E-liter 4K", "class": "チャージャー", "sub": "ジャンプビーコン", "sp": "テイオウイカ", "range": 5, "imageId": "Wst_Custom_E-liter_4K", "collection": "リッター4K" },
  { "name": "14式竹筒銃・乙", "name_en": "Bamboozler 14 Mk III", "class": "チャージャー", "sub": "タンサンボム", "sp": "デコイチラシ", "range": 4, "imageId": "Wst_Bamboozler_14_Mk_III", "collection": "14式竹筒銃" },
  { "name": "14式竹筒銃・甲", "name_en": "Bamboozler 14 Mk I", "class": "チャージャー", "sub": "ロボットボム", "sp": "メガホンレーザー5.1ch", "range": 4, "imageId": "Wst_Bamboozler_14_Mk_I", "collection": "14式竹筒銃" },
  { "name": "ソイチューバー", "name_en": "Goo Tuber", "class": "チャージャー", "sub": "トーピード", "sp": "マルチミサイル", "range": 4, "imageId": "Wst_Goo_Tuber", "collection": "ソイチューバー" },
  { "name": "4Kスコープ", "name_en": "E-liter 4K Scope", "class": "チャージャー", "sub": "トラップ", "sp": "ホップソナー", "range": 5, "imageId": "Wst_E-liter_4K_Scope", "collection": "リッター4K" },
  { "name": "ソイチューバーカスタム", "name_en": "Custom Goo Tuber", "class": "チャージャー", "sub": "タンサンボム", "sp": "ウルトラハンコ", "range": 4, "imageId": "Wst_Custom_Goo_Tuber", "collection": "ソイチューバー" },
  { "name": "4Kスコープカスタム", "name_en": "Custom E-liter 4K Scope", "class": "チャージャー", "sub": "ジャンプビーコン", "sp": "テイオウイカ", "range": 5, "imageId": "Wst_Custom_E-liter_4K_Scope", "collection": "リッター4K" },
  { "name": "オーダーブラスターレプリカ", "name_en": "Order Blaster Replica", "class": "ブラスター", "sub": "スプラッシュボム", "sp": "ショクワンダー", "range": 2, "imageId": "Wst_Order_Blaster_Replica", "collection": "ホットブラスター" },
  { "name": "ホットブラスター", "name_en": "Blaster", "class": "ブラスター", "sub": "ロボットボム", "sp": "グレートバリア", "range": 2, "imageId": "Wst_Blaster", "collection": "ホットブラスター" },
  { "name": "ラピッドブラスター", "name_en": "Rapid Blaster", "class": "ブラスター", "sub": "トラップ", "sp": "トリプルトルネード", "range": 3, "imageId": "Wst_Rapid_Blaster", "collection": "ラピッドブラスター" },
  { "name": "ホットブラスターカスタム", "name_en": "Custom Blaster", "class": "ブラスター", "sub": "ポイントセンサー", "sp": "ウルトラチャクチ", "range": 2, "imageId": "Wst_Custom_Blaster", "collection": "ホットブラスター" },
  { "name": "ホットブラスター艶", "name_en": "Kensa Blaster", "class": "ブラスター", "sub": "ジャンプビーコン", "sp": "カニタンク", "range": 2, "imageId": "Wst_Kensa_Blaster", "collection": "ホットブラスター" },
  { "name": "ラピッドブラスターデコ", "name_en": "Rapid Blaster Deco", "class": "ブラスター", "sub": "トーピード", "sp": "ジェットパック", "range": 3, "imageId": "Wst_Rapid_Blaster_Deco", "collection": "ラピッドブラスター" },
  { "name": "ロングブラスター", "name_en": "Range Blaster", "class": "ブラスター", "sub": "キューバンボム", "sp": "ホップソナー", "range": 4, "imageId": "Wst_Range_Blaster", "collection": "ロングブラスター" },
  { "name": "ノヴァブラスター", "name_en": "Luna Blaster", "class": "ブラスター", "sub": "スプラッシュボム", "sp": "ショクワンダー", "range": 1, "imageId": "Wst_Luna_Blaster", "collection": "ノヴァブラスター" },
  { "name": "ロングブラスターカスタム", "name_en": "Custom Range Blaster", "class": "ブラスター", "sub": "スプラッシュボム", "sp": "テイオウイカ", "range": 4, "imageId": "Wst_Custom_Range_Blaster", "collection": "ロングブラスター" },
  { "name": "S-BLAST92", "name_en": "S-BLAST '92", "class": "ブラスター", "sub": "スプリンクラー", "sp": "サメライド", "range": 3, "imageId": "Wst_S-BLAST_92", "collection": "S-BLAST" },
  { "name": "クラッシュブラスター", "name_en": "Clash Blaster", "class": "ブラスター", "sub": "スプラッシュボム", "sp": "ウルトラショット", "range": 1, "imageId": "Wst_Clash_Blaster", "collection": "クラッシュブラスター" },
  { "name": "ノヴァブラスターネオ", "name_en": "Luna Blaster Neo", "class": "ブラスター", "sub": "タンサンボム", "sp": "ウルトラハンコ", "range": 1, "imageId": "Wst_Luna_Blaster_Neo", "collection": "ノヴァブラスター" },
  { "name": "クラッシュブラスターネオ", "name_en": "Clash Blaster Neo", "class": "ブラスター", "sub": "カーリングボム", "sp": "デコイチラシ", "range": 1, "imageId": "Wst_Clash_Blaster_Neo", "collection": "クラッシュブラスター" },
  { "name": "Rブラスターエリート", "name_en": "Rapid Blaster Pro", "class": "ブラスター", "sub": "ポイズンミスト", "sp": "キューインキ", "range": 4, "imageId": "Wst_Rapid_Blaster_Pro", "collection": "Rブラスター" },
  { "name": "S-BLAST91", "name_en": "S-BLAST '91", "class": "ブラスター", "sub": "クイックボム", "sp": "ナイスダマ", "range": 3, "imageId": "Wst_S-BLAST_91", "collection": "S-BLAST" },
  { "name": "Rブラスターエリートデコ", "name_en": "Rapid Blaster Pro Deco", "class": "ブラスター", "sub": "ラインマーカー", "sp": "メガホンレーザー5.1ch", "range": 4, "imageId": "Wst_Rapid_Blaster_Pro_Deco", "collection": "Rブラスター" },
  { "name": "RブラスターエリートWNTR", "name_en": "Kensa Rapid Blaster Pro", "class": "ブラスター", "sub": "キューバンボム", "sp": "エナジースタンド", "range": 4, "imageId": "Wst_Kensa_Rapid_Blaster_Pro", "collection": "Rブラスター" },
  { "name": "オーダーローラーレプリカ", "name_en": "Order Roller Replica", "class": "ローラー", "sub": "カーリングボム", "sp": "グレートバリア", "range": 2, "imageId": "Wst_Order_Roller_Replica", "collection": "スプラローラー" },
  { "name": "スプラローラー", "name_en": "Splat Roller", "class": "ローラー", "sub": "カーリングボム", "sp": "グレートバリア", "range": 2, "imageId": "Wst_Splat_Roller", "collection": "スプラローラー" },
  { "name": "カーボンローラー", "name_en": "Carbon Roller", "class": "ローラー", "sub": "ロボットボム", "sp": "ショクワンダー", "range": 1, "imageId": "Wst_Carbon_Roller", "collection": "カーボンローラー" },
  { "name": "スプラローラーコラボ", "name_en": "Krak-On Splat Roller", "class": "ローラー", "sub": "ジャンプビーコン", "sp": "テイオウイカ", "range": 2, "imageId": "Wst_Krak-On_Splat_Roller", "collection": "スプラローラー" },
  { "name": "ダイナモローラー", "name_en": "Dynamo Roller", "class": "ローラー", "sub": "スプリンクラー", "sp": "エナジースタンド", "range": 3, "imageId": "Wst_Dynamo_Roller", "collection": "ダイナモローラー" },
  { "name": "ワイドローラー", "name_en": "Big Swig Roller", "class": "ローラー", "sub": "スプラッシュシールド", "sp": "キューインキ", "range": 3, "imageId": "Wst_Big_Swig_Roller", "collection": "ワイドローラー" },
  { "name": "ダイナモローラーテスラ", "name_en": "Gold Dynamo Roller", "class": "ローラー", "sub": "スプラッシュボム", "sp": "デコイチラシ", "range": 3, "imageId": "Wst_Gold_Dynamo_Roller", "collection": "ダイナモローラー" },
  { "name": "ダイナモローラー冥", "name_en": "Kensa Dynamo Roller", "class": "ローラー", "sub": "ポイントセンサー", "sp": "メガホンレーザー5.1ch", "range": 3, "imageId": "Wst_Kensa_Dynamo_Roller", "collection": "ダイナモローラー" },
  { "name": "ワイドローラーコラボ", "name_en": "Big Swig Roller Express", "class": "ローラー", "sub": "ラインマーカー", "sp": "アメフラシ", "range": 3, "imageId": "Wst_Big_Swig_Roller_Express", "collection": "ワイドローラー" },
  { "name": "ヴァリアブルローラー", "name_en": "Flingza Roller", "class": "ローラー", "sub": "トラップ", "sp": "マルチミサイル", "range": 3, "imageId": "Wst_Flingza_Roller", "collection": "ヴァリアブルローラー" },
  { "name": "ワイドローラー惑", "name_en": "Foil Big Swig Roller", "class": "ローラー", "sub": "トーピード", "sp": "ウルトラハンコ", "range": 3, "imageId": "Wst_Foil_Big_Swig_Roller", "collection": "ワイドローラー" },
  { "name": "カーボンローラーデコ", "name_en": "Carbon Roller Deco", "class": "ローラー", "sub": "クイックボム", "sp": "ウルトラショット", "range": 1, "imageId": "Wst_Carbon_Roller_Deco", "collection": "カーボンローラー" },
  { "name": "カーボンローラーANGL", "name_en": "Annaki Carbon Roller", "class": "ローラー", "sub": "タンサンボム", "sp": "デコイチラシ", "range": 1, "imageId": "Wst_Annaki_Carbon_Roller", "collection": "カーボンローラー" },
  { "name": "ヴァリアブルローラーフォイル", "name_en": "Foil Flingza Roller", "class": "ローラー", "sub": "キューバンボム", "sp": "スミナガシート", "range": 3, "imageId": "Wst_Foil_Flingza_Roller", "collection": "ヴァリアブルローラー" },
  { "name": "オーダーブラシレプリカ", "name_en": "Order Brush Replica", "class": "フデ", "sub": "キューバンボム", "sp": "ショクワンダー", "range": 1, "imageId": "Wst_Order_Brush_Replica", "collection": "ホクサイ" },
  { "name": "ホクサイ", "name_en": "Octobrush", "class": "フデ", "sub": "キューバンボム", "sp": "ショクワンダー", "range": 1, "imageId": "Wst_Octobrush", "collection": "ホクサイ" },
  { "name": "パブロ", "name_en": "Inkbrush", "class": "フデ", "sub": "スプラッシュボム", "sp": "メガホンレーザー5.1ch", "range": 1, "imageId": "Wst_Inkbrush", "collection": "パブロ" },
  { "name": "ホクサイ・ヒュー", "name_en": "Octobrush Nouveau", "class": "フデ", "sub": "ジャンプビーコン", "sp": "アメフラシ", "range": 1, "imageId": "Wst_Octobrush_Nouveau", "collection": "ホクサイ" },
  { "name": "ホクサイ彗", "name_en": "Kensa Octobrush", "class": "フデ", "sub": "ロボットボム", "sp": "テイオウイカ", "range": 1, "imageId": "Wst_Kensa_Octobrush", "collection": "ホクサイ" },
  { "name": "フィンセント", "name_en": "Painbrush", "class": "フデ", "sub": "カーリングボム", "sp": "ホップソナー", "range": 2, "imageId": "Wst_Painbrush", "collection": "フィンセント" },
  { "name": "パブロ・ヒュー", "name_en": "Inkbrush Nouveau", "class": "フデ", "sub": "トラップ", "sp": "ウルトラハンコ", "range": 1, "imageId": "Wst_Inkbrush_Nouveau", "collection": "パブロ" },
  { "name": "フィンセント・ヒュー", "name_en": "Painbrush Nouveau", "class": "フデ", "sub": "ポイントセンサー", "sp": "マルチミサイル", "range": 2, "imageId": "Wst_Painbrush_Nouveau", "collection": "フィンセント" },
  { "name": "フィンセントBRNZ", "name_en": "Bronze Painbrush", "class": "フデ", "sub": "スプラッシュシールド", "sp": "ウルトラショット", "range": 2, "imageId": "Wst_Bronze_Painbrush", "collection": "フィンセント" },
  { "name": "オーダースロッシャーレプリカ", "name_en": "Order Slosher Replica", "class": "スロッシャー", "sub": "スプラッシュボム", "sp": "トリプルトルネード", "range": 2, "imageId": "Wst_Order_Slosher_Replica", "collection": "バケットスロッシャー" },
  { "name": "バケットスロッシャー", "name_en": "Slosher", "class": "スロッシャー", "sub": "スプラッシュボム", "sp": "トリプルトルネード", "range": 2, "imageId": "Wst_Slosher", "collection": "バケットスロッシャー" },
  { "name": "ヒッセン", "name_en": "Tri-Slosher", "class": "スロッシャー", "sub": "ポイズンミスト", "sp": "ジェットパック", "range": 1, "imageId": "Wst_Tri-Slosher", "collection": "ヒッセン" },
  { "name": "バケットスロッシャーデコ", "name_en": "Slosher Deco", "class": "スロッシャー", "sub": "ラインマーカー", "sp": "ショクワンダー", "range": 2, "imageId": "Wst_Slosher_Deco", "collection": "バケットスロッシャー" },
  { "name": "スクリュースロッシャー", "name_en": "Sloshing Machine", "class": "スロッシャー", "sub": "タンサンボム", "sp": "ナイスダマ", "range": 3, "imageId": "Wst_Sloshing_Machine", "collection": "スクリュースロッシャー" },
  { "name": "モップリン", "name_en": "Dread Wringer", "class": "スロッシャー", "sub": "キューバンボム", "sp": "サメライド", "range": 3, "imageId": "Wst_Dread_Wringer", "collection": "モップリン" },
  { "name": "ヒッセン・ヒュー", "name_en": "Tri-Slosher Nouveau", "class": "スロッシャー", "sub": "タンサンボム", "sp": "エナジースタンド", "range": 1, "imageId": "Wst_Tri-Slosher_Nouveau", "collection": "ヒッセン" },
  { "name": "モップリンD", "name_en": "Dread Wringer D", "class": "スロッシャー", "sub": "ジャンプビーコン", "sp": "ホップソナー", "range": 3, "imageId": "Wst_Dread_Wringer_D", "collection": "モップリン" },
  { "name": "ヒッセンASH", "name_en": "Annaki Tri-Slosher", "class": "スロッシャー", "sub": "スプラッシュボム", "sp": "スミナガシート", "range": 1, "imageId": "Wst_Annaki_Tri-Slosher", "collection": "ヒッセン" },
  { "name": "オーバーフロッシャー", "name_en": "Bloblobber", "class": "スロッシャー", "sub": "スプリンクラー", "sp": "アメフラシ", "range": 4, "imageId": "Wst_Bloblobber", "collection": "オーバーフロッシャー" },
  { "name": "モップリン角", "name_en": "Kensa Dread Wringer", "class": "スロッシャー", "sub": "カーリングボム", "sp": "カニタンク", "range": 3, "imageId": "Wst_Kensa_Dread_Wringer", "collection": "モップリン" },
  { "name": "スクリュースロッシャーネオ", "name_en": "Sloshing Machine Neo", "class": "スロッシャー", "sub": "ポイントセンサー", "sp": "ウルトラショット", "range": 3, "imageId": "Wst_Sloshing_Machine_Neo", "collection": "スクリュースロッシャー" },
  { "name": "オーバーフロッシャーデコ", "name_en": "Bloblobber Deco", "class": "スロッシャー", "sub": "ラインマーカー", "sp": "テイオウイカ", "range": 4, "imageId": "Wst_Bloblobber_Deco", "collection": "オーバーフロッシャー" },
  { "name": "エクスプロッシャー", "name_en": "Explosher", "class": "スロッシャー", "sub": "ポイントセンサー", "sp": "アメフラシ", "range": 5, "imageId": "Wst_Explosher", "collection": "エクスプロッシャー" },
  { "name": "エクスプロッシャーカスタム", "name_en": "Custom Explosher", "class": "スロッシャー", "sub": "スプラッシュシールド", "sp": "ウルトラチャクチ", "range": 5, "imageId": "Wst_Custom_Explosher", "collection": "エクスプロッシャー" },
  { "name": "オーダースピナーレプリカ", "name_en": "Order Splatling Replica", "class": "スピナー", "sub": "スプリンクラー", "sp": "ホップソナー", "range": 4, "imageId": "Wst_Order_Splatling_Replica", "collection": "バレルスピナー" },
  { "name": "バレルスピナー", "name_en": "Heavy Splatling", "class": "スピナー", "sub": "スプリンクラー", "sp": "ホップソナー", "range": 4, "imageId": "Wst_Heavy_Splatling", "collection": "バレルスピナー" },
  { "name": "スプラスピナー", "name_en": "Mini Splatling", "class": "スピナー", "sub": "クイックボム", "sp": "ウルトラハンコ", "range": 3, "imageId": "Wst_Mini_Splatling", "collection": "スプラスピナー" },
  { "name": "イグザミナー", "name_en": "Heavy Edit Splatling", "class": "スピナー", "sub": "カーリングボム", "sp": "エナジースタンド", "range": 4, "imageId": "Wst_Heavy_Edit_Splatling", "collection": "イグザミナー" },
  { "name": "バレルスピナーデコ", "name_en": "Heavy Splatling Deco", "class": "スピナー", "sub": "ポイントセンサー", "sp": "テイオウイカ", "range": 4, "imageId": "Wst_Heavy_Splatling_Deco", "collection": "バレルスピナー" },
  { "name": "イグザミナー・ヒュー", "name_en": "Heavy Edit Splatling Nouveau", "class": "スピナー", "sub": "スプラッシュボム", "sp": "カニタンク", "range": 4, "imageId": "Wst_Heavy_Edit_Splatling_Nouveau", "collection": "イグザミナー" },
  { "name": "ハイドラント", "name_en": "Hydra Splatling", "class": "スピナー", "sub": "ロボットボム", "sp": "ナイスダマ", "range": 5, "imageId": "Wst_Hydra_Splatling", "collection": "ハイドラント" },
  { "name": "ハイドラントカスタム", "name_en": "Custom Hydra Splatling", "class": "スピナー", "sub": "トラップ", "sp": "スミナガシート", "range": 5, "imageId": "Wst_Custom_Hydra_Splatling", "collection": "ハイドラント" },
  { "name": "スプラスピナーコラボ", "name_en": "Zink Mini Splatling", "class": "スピナー", "sub": "ポイズンミスト", "sp": "グレートバリア", "range": 3, "imageId": "Wst_Zink_Mini_Splatling", "collection": "スプラスピナー" },
  { "name": "ハイドラント圧", "name_en": "Kensa Hydra Splatling", "class": "スピナー", "sub": "スプリンクラー", "sp": "グレートバリア", "range": 5, "imageId": "Wst_Kensa_Hydra_Splatling", "collection": "ハイドラント" },
  { "name": "スプラスピナーPYTN", "name_en": "Kensa Mini Splatling", "class": "スピナー", "sub": "ジャンプビーコン", "sp": "ウルトラショット", "range": 3, "imageId": "Wst_Kensa_Mini_Splatling", "collection": "スプラスピナー" },
  { "name": "ノーチラス79", "name_en": "Nautilus 79", "class": "スピナー", "sub": "キューバンボム", "sp": "ウルトラチャクチ", "range": 4, "imageId": "Wst_Nautilus_79", "collection": "ノーチラス" },
  { "name": "ノーチラス47", "name_en": "Nautilus 47", "class": "スピナー", "sub": "ポイントセンサー", "sp": "アメフラシ", "range": 4, "imageId": "Wst_Nautilus_47", "collection": "ノーチラス" },
  { "name": "クーゲルシュライバー・ヒュー", "name_en": "Ballpoint Splatling Nouveau", "class": "スピナー", "sub": "トラップ", "sp": "キューインキ", "range": 5, "imageId": "Wst_Ballpoint_Splatling_Nouveau", "collection": "クーゲルシュライバー" },
  { "name": "クーゲルシュライバー", "name_en": "Ballpoint Splatling", "class": "スピナー", "sub": "タンサンボム", "sp": "ジェットパック", "range": 5, "imageId": "Wst_Ballpoint_Splatling", "collection": "クーゲルシュライバー" },
  { "name": "オーダーマニューバーレプリカ", "name_en": "Order Dualie Replicas", "class": "マニューバー", "sub": "キューバンボム", "sp": "カニタンク", "range": 2, "imageId": "Wst_Order_Dualie_Replicas", "collection": "スプラマニューバー" },
  { "name": "スプラマニューバー", "name_en": "Splat Dualies", "class": "マニューバー", "sub": "キューバンボム", "sp": "カニタンク", "range": 2, "imageId": "Wst_Splat_Dualies", "collection": "スプラマニューバー" },
  { "name": "デュアルスイーパー", "name_en": "Dualie Squelchers", "class": "マニューバー", "sub": "スプラッシュボム", "sp": "ホップソナー", "range": 3, "imageId": "Wst_Dualie_Squelchers", "collection": "デュアルスイーパー" },
  { "name": "スプラマニューバーコラボ", "name_en": "Enperry Splat Dualies", "class": "マニューバー", "sub": "カーリングボム", "sp": "ウルトラチャクチ", "range": 2, "imageId": "Wst_Enperry_Splat_Dualies", "collection": "スプラマニューバー" },
  { "name": "スパッタリー", "name_en": "Dapple Dualies", "class": "マニューバー", "sub": "ジャンプビーコン", "sp": "エナジースタンド", "range": 1, "imageId": "Wst_Dapple_Dualies", "collection": "スパッタリー" },
  { "name": "スプラマニューバー耀", "name_en": "Kensa Splat Dualies", "class": "マニューバー", "sub": "タンサンボム", "sp": "グレートバリア", "range": 2, "imageId": "Wst_Kensa_Splat_Dualies", "collection": "スプラマニューバー" },
  { "name": "デュアルスイーパーカスタム", "name_en": "Custom Dualie Squelchers", "class": "マニューバー", "sub": "ジャンプビーコン", "sp": "デコイチラシ", "range": 3, "imageId": "Wst_Custom_Dualie_Squelchers", "collection": "デュアルスイーパー" },
  { "name": "クアッドホッパーブラック", "name_en": "Dark Tetra Dualies", "class": "マニューバー", "sub": "ロボットボム", "sp": "サメライド", "range": 2, "imageId": "Wst_Dark_Tetra_Dualies", "collection": "クアッドホッパー" },
  { "name": "デュアルスイーパー蹄", "name_en": "Annaki Dualie Squelchers", "class": "マニューバー", "sub": "ポイントセンサー", "sp": "スミナガシート", "range": 3, "imageId": "Wst_Annaki_Dualie_Squelchers", "collection": "デュアルスイーパー" },
  { "name": "ケルビン525", "name_en": "Glooga Dualies", "class": "マニューバー", "sub": "スプラッシュシールド", "sp": "ナイスダマ", "range": 3, "imageId": "Wst_Glooga_Dualies", "collection": "ケルビン525" },
  { "name": "クアッドホッパーホワイト", "name_en": "Light Tetra Dualies", "class": "マニューバー", "sub": "スプリンクラー", "sp": "ショクワンダー", "range": 2, "imageId": "Wst_Light_Tetra_Dualies", "collection": "クアッドホッパー" },
  { "name": "スパッタリー・ヒュー", "name_en": "Dapple Dualies Nouveau", "class": "マニューバー", "sub": "トーピード", "sp": "サメライド", "range": 1, "imageId": "Wst_Dapple_Dualies_Nouveau", "collection": "スパッタリー" },
  { "name": "ケルビン525デコ", "name_en": "Glooga Dualies Deco", "class": "マニューバー", "sub": "ポイントセンサー", "sp": "ウルトラショット", "range": 3, "imageId": "Wst_Glooga_Dualies_Deco", "collection": "ケルビン525" },
  { "name": "スパッタリーOWL", "name_en": "Annaki Dapple Dualies", "class": "マニューバー", "sub": "スプラッシュボム", "sp": "メガホンレーザー5.1ch", "range": 1, "imageId": "Wst_Annaki_Dapple_Dualies", "collection": "スパッタリー" },
  { "name": "オーダーシェルターレプリカ", "name_en": "Order Brella Replica", "class": "シェルター", "sub": "スプリンクラー", "sp": "トリプルトルネード", "range": 2, "imageId": "Wst_Order_Brella_Replica", "collection": "パラシェルター" },
  { "name": "パラシェルター", "name_en": "Splat Brella", "class": "シェルター", "sub": "スプリンクラー", "sp": "トリプルトルネード", "range": 2, "imageId": "Wst_Splat_Brella", "collection": "パラシェルター" },
  { "name": "24式張替傘・甲", "name_en": "Recycled Brella 24 Mk I", "class": "シェルター", "sub": "ラインマーカー", "sp": "グレートバリア", "range": 2, "imageId": "Wst_Recycled_Brella_24_Mk_I", "collection": "24式張替傘" },
  { "name": "キャンピングシェルター", "name_en": "Tenta Brella", "class": "シェルター", "sub": "ジャンプビーコン", "sp": "キューインキ", "range": 1, "imageId": "Wst_Tenta_Brella", "collection": "キャンピングシェルター" },
  { "name": "スパイガジェット", "name_en": "Undercover Brella", "class": "シェルター", "sub": "トラップ", "sp": "サメライド", "range": 1, "imageId": "Wst_Undercover_Brella", "collection": "スパイガジェット" },
  { "name": "パラシェルターソレーラ", "name_en": "Sorella Brella", "class": "シェルター", "sub": "ロボットボム", "sp": "ジェットパック", "range": 2, "imageId": "Wst_Sorella_Brella", "collection": "パラシェルター" },
  { "name": "24式張替傘・乙", "name_en": "Recycled Brella 24 Mk II", "class": "シェルター", "sub": "ポイズンミスト", "sp": "ウルトラチャクチ", "range": 2, "imageId": "Wst_Recycled_Brella_24_Mk_II", "collection": "24式張替傘" },
  { "name": "キャンピングシェルターソレーラ", "name_en": "Tenta Sorella Brella", "class": "シェルター", "sub": "トラップ", "sp": "ウルトラショット", "range": 1, "imageId": "Wst_Tenta_Sorella_Brella", "collection": "キャンピングシェルター" },
  { "name": "スパイガジェットソレーラ", "name_en": "Undercover Sorella Brella", "class": "シェルター", "sub": "トーピード", "sp": "スミナガシート", "range": 1, "imageId": "Wst_Undercover_Sorella_Brella", "collection": "スパイガジェット" },
  { "name": "キャンピングシェルターCREM", "name_en": "Mint-Camo Tenta Brella", "class": "シェルター", "sub": "ポイズンミスト", "sp": "デコイチラシ", "range": 1, "imageId": "Wst_Mint-Camo_Tenta_Brella", "collection": "キャンピングシェルター" },
  { "name": "スパイガジェット繚", "name_en": "Kensa Undercover Brella", "class": "シェルター", "sub": "カーリングボム", "sp": "メガホンレーザー5.1ch", "range": 1, "imageId": "Wst_Kensa_Undercover_Brella", "collection": "スパイガジェット" },
  { "name": "オーダーワイパーレプリカ", "name_en": "Order Splatana Replica", "class": "ワイパー", "sub": "クイックボム", "sp": "ショクワンダー", "range": 2, "imageId": "Wst_Order_Splatana_Replica", "collection": "ジムワイパー" },
  { "name": "ドライブワイパー", "name_en": "Splatana Wiper", "class": "ワイパー", "sub": "トーピード", "sp": "ウルトラハンコ", "range": 2, "imageId": "Wst_Splatana_Wiper", "collection": "ドライブワイパー" },
  { "name": "ドライブワイパーデコ", "name_en": "Splatana Wiper Deco", "class": "ワイパー", "sub": "ジャンプビーコン", "sp": "マルチミサイル", "range": 2, "imageId": "Wst_Splatana_Wiper_Deco", "collection": "ドライブワイパー" },
  { "name": "ドライブワイパーRUST", "name_en": "Steel-Head Splatana Wiper", "class": "ワイパー", "sub": "カーリングボム", "sp": "ウルトラショット", "range": 2, "imageId": "Wst_Steel-Head_Splatana_Wiper", "collection": "ドライブワイパー" },
  { "name": "ジムワイパー", "name_en": "Splatana Stamper", "class": "ワイパー", "sub": "クイックボム", "sp": "ショクワンダー", "range": 3, "imageId": "Wst_Splatana_Stamper", "collection": "ジムワイパー" },
  { "name": "ジムワイパー・ヒュー", "name_en": "Splatana Stamper Nouveau", "class": "ワイパー", "sub": "ポイズンミスト", "sp": "カニタンク", "range": 3, "imageId": "Wst_Splatana_Stamper_Nouveau", "collection": "ジムワイパー" },
  { "name": "デンタルワイパーミント", "name_en": "Mint Decavitator", "class": "ワイパー", "sub": "キューバンボム", "sp": "グレートバリア", "range": 3, "imageId": "Wst_Mint_Decavitator", "collection": "デンタルワイパー" },
  { "name": "ジムワイパー封", "name_en": "Kensa Splatana Stamper", "class": "ワイパー", "sub": "ロボットボム", "sp": "ナイスダマ", "range": 3, "imageId": "Wst_Kensa_Splatana_Stamper", "collection": "ジムワイパー" },
  { "name": "デンタルワイパースミ", "name_en": "Charcoal Decavitator", "class": "ワイパー", "sub": "スプラッシュシールド", "sp": "ジェットパック", "range": 3, "imageId": "Wst_Charcoal_Decavitator", "collection": "デンタルワイパー" },
  { "name": "オーダーストリンガーレプリカ", "name_en": "Order Stringer Replica", "class": "ストリンガー", "sub": "ポイズンミスト", "sp": "メガホンレーザー5.1ch", "range": 4, "imageId": "Wst_Order_Stringer_Replica", "collection": "トライストリンガー" },
  { "name": "トライストリンガー", "name_en": "Tri-Stringer", "class": "ストリンガー", "sub": "ポイズンミスト", "sp": "メガホンレーザー5.1ch", "range": 4, "imageId": "Wst_Tri-Stringer", "collection": "トライストリンガー" },
  { "name": "LACT450", "name_en": "REEF-LUX 450", "class": "ストリンガー", "sub": "カーリングボム", "sp": "マルチミサイル", "range": 2, "imageId": "Wst_REEF-LUX_450", "collection": "LACT-450" },
  { "name": "トライストリンガーコラボ", "name_en": "Inkline Tri-Stringer", "class": "ストリンガー", "sub": "スプリンクラー", "sp": "デコイチラシ", "range": 4, "imageId": "Wst_Inkline_Tri-Stringer", "collection": "トライストリンガー" },
  { "name": "LACT-450デコ", "name_en": "REEF-LUX 450 Deco", "class": "ストリンガー", "sub": "スプラッシュシールド", "sp": "サメライド", "range": 2, "imageId": "Wst_REEF-LUX_450_Deco", "collection": "LACT-450" },
  { "name": "トライストリンガー燈", "name_en": "Kensa Tri-Stringer", "class": "ストリンガー", "sub": "ラインマーカー", "sp": "ジェットパック", "range": 4, "imageId": "Wst_Kensa_Tri-Stringer", "collection": "トライストリンガー" },
  { "name": "LACT-450MILK", "name_en": "Annaki REEF-LUX 450", "class": "ストリンガー", "sub": "トーピード", "sp": "ナイスダマ", "range": 2, "imageId": "Wst_Annaki_REEF-LUX_450", "collection": "LACT-450" },
  { "name": "フルイドV", "name_en": "Wellstring V", "class": "ストリンガー", "sub": "ロボットボム", "sp": "ウルトラハンコ", "range": 4, "imageId": "Wst_Wellstring_V", "collection": "フルイド" },
  { "name": "フルイドVカスタム", "name_en": "Custom Wellstring V", "class": "ストリンガー", "sub": "ポイントセンサー", "sp": "ホップソナー", "range": 4, "imageId": "Wst_Custom_Wellstring_V", "collection": "フルイド" }
];
