const weapons = [
  { "name": "わかばシューター", "name_en": "Splattershot Jr.", "class": "シューター", "sub": "スプラッシュボム", "sp": "グレートバリア", "range": 1 },
  { "name": "オーダーシューターレプリカ", "name_en": "Order Shot Replica", "class": "シューター", "sub": "キューバンボム", "sp": "ウルトラショット", "range": 2 },
  { "name": "オクタシューターレプリカ", "name_en": "Octoshot Replica", "class": "シューター", "sub": "スプラッシュボム", "sp": "トリプルトルネード", "range": 2 },
  { "name": "ヒーローシューターレプリカ", "name_en": "Hero Shot Replica", "class": "シューター", "sub": "キューバンボム", "sp": "ウルトラショット", "range": 2 },
  { "name": "スプラシューター", "name_en": "Splattershot", "class": "シューター", "sub": "キューバンボム", "sp": "ウルトラショット", "range": 2 },
  { "name": "プロモデラーMG", "name_en": "Aerospray MG", "class": "シューター", "sub": "タンサンボム", "sp": "サメライド", "range": 1 },
  { "name": "N-ZAP85", "name_en": "N-ZAP '85", "class": "シューター", "sub": "キューバンボム", "sp": "エナジースタンド", "range": 2 },
  { "name": "もみじシューター", "name_en": "Custom Splattershot Jr.", "class": "シューター", "sub": "トーピード", "sp": "ホップソナー", "range": 1 },
  { "name": "スペースシューター", "name_en": "Splattershot Nova", "class": "シューター", "sub": "ポイントセンサー", "sp": "メガホンレーザー5.1ch", "range": 3 },
  { "name": "ボールドマーカー", "name_en": "Sploosh-o-matic", "class": "シューター", "sub": "カーリングボム", "sp": "ウルトラハンコ", "range": 1 },
  { "name": "プライムシューター", "name_en": "Splattershot Pro", "class": "シューター", "sub": "ラインマーカー", "sp": "カニタンク", "range": 3 },
  { "name": "スプラシューターコラボ", "name_en": "Tentatek Splattershot", "class": "シューター", "sub": "スプラッシュボム", "sp": "トリプルトルネード", "range": 2 },
  { "name": "N-ZAP89", "name_en": "N-ZAP '89", "class": "シューター", "sub": "ロボットボム", "sp": "デコイチラシ", "range": 2 },
  { "name": "52ガロン", "name_en": ".52 Gal", "class": "シューター", "sub": "スプラッシュシールド", "sp": "メガホンレーザー5.1ch", "range": 2 },
  { "name": "スペースシューターコラボ", "name_en": "Annaki Splattershot Nova", "class": "シューター", "sub": "トラップ", "sp": "ジェットパック", "range": 3 },
  { "name": "スプラシューター煌", "name_en": "Kensa Splattershot", "class": "シューター", "sub": "クイックボム", "sp": "テイオウイカ", "range": 2 },
  { "name": "ボールドマーカーネオ", "name_en": "Neo Sploosh-o-matic", "class": "シューター", "sub": "ジャンプビーコン", "sp": "メガホンレーザー5.1ch", "range": 1 },
  { "name": "L3リールガン", "name_en": "L-3 Nozzlenose", "class": "シューター", "sub": "カーリングボム", "sp": "カニタンク", "range": 3 },
  { "name": "52ガロンデコ", "name_en": ".52 Gal Deco", "class": "シューター", "sub": "カーリングボム", "sp": "スミナガシート", "range": 2 },
  { "name": "ジェットスイーパー", "name_en": "Jet Squelcher", "class": "シューター", "sub": "ラインマーカー", "sp": "キューインキ", "range": 5 },
  { "name": "シャープマーカー", "name_en": "Splash-o-matic", "class": "シューター", "sub": "クイックボム", "sp": "カニタンク", "range": 2 },
  { "name": "96ガロン", "name_en": ".96 Gal", "class": "シューター", "sub": "スプリンクラー", "sp": "キューインキ", "range": 3 },
  { "name": "プロモデラーRG", "name_en": "Aerospray RG", "class": "シューター", "sub": "スプリンクラー", "sp": "ナイスダマ", "range": 1 },
  { "name": "L3リールガンD", "name_en": "L-3 Nozzlenose D", "class": "シューター", "sub": "クイックボム", "sp": "ウルトラハンコ", "range": 3 },
  { "name": "プロモデラー彩", "name_en": "Aerospray PG", "class": "シューター", "sub": "クイックボム", "sp": "スミナガシート", "range": 1 },
  { "name": "ボトルガイザー", "name_en": "Squeezer", "class": "シューター", "sub": "スプラッシュシールド", "sp": "ウルトラショット", "range": 4 },
  { "name": "プライムシューターコラボ", "name_en": "Forge Splattershot Pro", "class": "シューター", "sub": "キューバンボム", "sp": "ナイスダマ", "range": 3 },
  { "name": "L3リールガン箔", "name_en": "Foil L-3 Nozzlenose", "class": "シューター", "sub": "スプラッシュボム", "sp": "ジェットパック", "range": 3 },
  { "name": "ジェットスイーパーカスタム", "name_en": "Custom Jet Squelcher", "class": "シューター", "sub": "ポイズンミスト", "sp": "アメフラシ", "range": 5 },
  { "name": "ジェットスイーパーCOBR", "name_en": "Mint-Camo Jet Squelcher", "class": "シューター", "sub": "クイックボム", "sp": "ウルトラチャクチ", "range": 5 },
  { "name": "シャープマーカーネオ", "name_en": "Neo Splash-o-matic", "class": "シューター", "sub": "キューバンボム", "sp": "トリプルトルネード", "range": 2 },
  { "name": "シャープマーカーGECK", "name_en": "Annaki Splash-o-matic", "class": "シューター", "sub": "ポイズンミスト", "sp": "マルチミサイル", "range": 2 },
  { "name": "96ガロンデコ", "name_en": ".96 Gal Deco", "class": "シューター", "sub": "スプラッシュシールド", "sp": "テイオウイカ", "range": 3 },
  { "name": "プライムシューターFRZN", "name_en": "Kensa Splattershot Pro", "class": "シューター", "sub": "スプラッシュボム", "sp": "マルチミサイル", "range": 3 },
  { "name": "H3リールガン", "name_en": "H-3 Nozzlenose", "class": "シューター", "sub": "ポイントセンサー", "sp": "エナジースタンド", "range": 4 },
  { "name": "96ガロン爪", "name_en": "Kensa .96 Gal", "class": "シューター", "sub": "ラインマーカー", "sp": "エナジースタンド", "range": 3 },
  { "name": "ボトルガイザーフォイル", "name_en": "Foil Squeezer", "class": "シューター", "sub": "ロボットボム", "sp": "スミナガシート", "range": 4 },
  { "name": "H3リールガンD", "name_en": "H-3 Nozzlenose D", "class": "シューター", "sub": "スプラッシュシールド", "sp": "グレートバリア", "range": 4 },
  { "name": "H3リールガンSNAK", "name_en": "Annaki H-3 Nozzlenose", "class": "シューター", "sub": "キューバンボム", "sp": "トリプルトルネード", "range": 4 },
  { "name": "オーダーチャージャーレプリカ", "name_en": "Order Charger Replica", "class": "チャージャー", "sub": "スプラッシュボム", "sp": "キューインキ", "range": 5 },
  { "name": "スプラチャージャー", "name_en": "Splat Charger", "class": "チャージャー", "sub": "スプラッシュボム", "sp": "キューインキ", "range": 5 },
  { "name": "スクイックリンα", "name_en": "Classic Squiffer", "class": "チャージャー", "sub": "ポイントセンサー", "sp": "グレートバリア", "range": 3 },
  { "name": "スプラチャージャーコラボ", "name_en": "Z+F Splat Charger", "class": "チャージャー", "sub": "スプラッシュシールド", "sp": "トリプルトルネード", "range": 5 },
  { "name": "スプラスコープ", "name_en": "Splatterscope", "class": "チャージャー", "sub": "スプラッシュボム", "sp": "キューインキ", "range": 5 },
  { "name": "スプラチャージャーFRST", "name_en": "Kensa Charger", "class": "チャージャー", "sub": "スプリンクラー", "sp": "カニタンク", "range": 5 },
  { "name": "スクイックリンβ", "name_en": "New Squiffer", "class": "チャージャー", "sub": "ロボットボム", "sp": "ショクワンダー", "range": 3 },
  { "name": "R-PEN/5H", "name_en": "Bamboozler 14 Mk I", "class": "チャージャー", "sub": "スプリンクラー", "sp": "エナジースタンド", "range": 4 },
  { "name": "スプラスコープコラボ", "name_en": "Z+F Splatterscope", "class": "チャージャー", "sub": "スプラッシュシールド", "sp": "トリプルトルネード", "range": 5 },
  { "name": "スプラスコープFRST", "name_en": "Kensa Splatterscope", "class": "チャージャー", "sub": "スプリンクラー", "sp": "カニタンク", "range": 5 },
  { "name": "リッター4K", "name_en": "E-liter 4K", "class": "チャージャー", "sub": "トラップ", "sp": "ホップソナー", "range": 5 },
  { "name": "R-PEN/5B", "name_en": "Bamboozler 14 Mk II", "class": "チャージャー", "sub": "スプラッシュシールド", "sp": "アメフラシ", "range": 4 },
  { "name": "リッター4Kカスタム", "name_en": "Custom E-liter 4K", "class": "チャージャー", "sub": "ジャンプビーコン", "sp": "テイオウイカ", "range": 5 },
  { "name": "14式竹筒銃・乙", "name_en": "Bamboozler 14 Mk III", "class": "チャージャー", "sub": "タンサンボム", "sp": "デコイチラシ", "range": 4 },
  { "name": "14式竹筒銃・甲", "name_en": "Bamboozler 14 Mk I", "class": "チャージャー", "sub": "ロボットボム", "sp": "メガホンレーザー5.1ch", "range": 4 },
  { "name": "ソイチューバー", "name_en": "Goo Tuber", "class": "チャージャー", "sub": "トーピード", "sp": "マルチミサイル", "range": 4 },
  { "name": "4Kスコープ", "name_en": "E-liter 4K Scope", "class": "チャージャー", "sub": "トラップ", "sp": "ホップソナー", "range": 5 },
  { "name": "ソイチューバーカスタム", "name_en": "Custom Goo Tuber", "class": "チャージャー", "sub": "タンサンボム", "sp": "ウルトラハンコ", "range": 4 },
  { "name": "4Kスコープカスタム", "name_en": "Custom E-liter 4K Scope", "class": "チャージャー", "sub": "ジャンプビーコン", "sp": "テイオウイカ", "range": 5 },
  { "name": "オーダーブラスターレプリカ", "name_en": "Order Blaster Replica", "class": "ブラスター", "sub": "スプラッシュボム", "sp": "ショクワンダー", "range": 2 },
  { "name": "ホットブラスター", "name_en": "Blaster", "class": "ブラスター", "sub": "ロボットボム", "sp": "グレートバリア", "range": 2 },
  { "name": "ラピッドブラスター", "name_en": "Rapid Blaster", "class": "ブラスター", "sub": "トラップ", "sp": "トリプルトルネード", "range": 3 },
  { "name": "ホットブラスターカスタム", "name_en": "Custom Blaster", "class": "ブラスター", "sub": "ポイントセンサー", "sp": "ウルトラチャクチ", "range": 2 },
  { "name": "ホットブラスター艶", "name_en": "Kensa Blaster", "class": "ブラスター", "sub": "ジャンプビーコン", "sp": "カニタンク", "range": 2 },
  { "name": "ラピッドブラスターデコ", "name_en": "Rapid Blaster Deco", "class": "ブラスター", "sub": "トーピード", "sp": "ジェットパック", "range": 3 },
  { "name": "ロングブラスター", "name_en": "Range Blaster", "class": "ブラスター", "sub": "キューバンボム", "sp": "ホップソナー", "range": 4 },
  { "name": "ノヴァブラスター", "name_en": "Luna Blaster", "class": "ブラスター", "sub": "スプラッシュボム", "sp": "ショクワンダー", "range": 1 },
  { "name": "ロングブラスターカスタム", "name_en": "Custom Range Blaster", "class": "ブラスター", "sub": "スプラッシュボム", "sp": "テイオウイカ", "range": 4 },
  { "name": "S-BLAST92", "name_en": "S-BLAST '92", "class": "ブラスター", "sub": "スプリンクラー", "sp": "サメライド", "range": 3 },
  { "name": "クラッシュブラスター", "name_en": "Clash Blaster", "class": "ブラスター", "sub": "スプラッシュボム", "sp": "ウルトラショット", "range": 1 },
  { "name": "ノヴァブラスターネオ", "name_en": "Luna Blaster Neo", "class": "ブラスター", "sub": "タンサンボム", "sp": "ウルトラハンコ", "range": 1 },
  { "name": "クラッシュブラスターネオ", "name_en": "Clash Blaster Neo", "class": "ブラスター", "sub": "カーリングボム", "sp": "デコイチラシ", "range": 1 },
  { "name": "Rブラスターエリート", "name_en": "Rapid Blaster Pro", "class": "ブラスター", "sub": "ポイズンミスト", "sp": "キューインキ", "range": 4 },
  { "name": "S-BLAST91", "name_en": "S-BLAST '91", "class": "ブラスター", "sub": "クイックボム", "sp": "ナイスダマ", "range": 3 },
  { "name": "Rブラスターエリートデコ", "name_en": "Rapid Blaster Pro Deco", "class": "ブラスター", "sub": "ラインマーカー", "sp": "メガホンレーザー5.1ch", "range": 4 },
  { "name": "RブラスターエリートWNTR", "name_en": "Kensa Rapid Blaster Pro", "class": "ブラスター", "sub": "キューバンボム", "sp": "エナジースタンド", "range": 4 },
  { "name": "オーダーローラーレプリカ", "name_en": "Order Roller Replica", "class": "ローラー", "sub": "カーリングボム", "sp": "グレートバリア", "range": 2 },
  { "name": "スプラローラー", "name_en": "Splat Roller", "class": "ローラー", "sub": "カーリングボム", "sp": "グレートバリア", "range": 2 },
  { "name": "カーボンローラー", "name_en": "Carbon Roller", "class": "ローラー", "sub": "ロボットボム", "sp": "ショクワンダー", "range": 1 },
  { "name": "スプラローラーコラボ", "name_en": "Krak-On Splat Roller", "class": "ローラー", "sub": "ジャンプビーコン", "sp": "テイオウイカ", "range": 2 },
  { "name": "ダイナモローラー", "name_en": "Dynamo Roller", "class": "ローラー", "sub": "スプリンクラー", "sp": "エナジースタンド", "range": 3 },
  { "name": "ワイドローラー", "name_en": "Big Swig Roller", "class": "ローラー", "sub": "スプラッシュシールド", "sp": "キューインキ", "range": 3 },
  { "name": "ダイナモローラーテスラ", "name_en": "Gold Dynamo Roller", "class": "ローラー", "sub": "スプラッシュボム", "sp": "デコイチラシ", "range": 3 },
  { "name": "ダイナモローラー冥", "name_en": "Kensa Dynamo Roller", "class": "ローラー", "sub": "ポイントセンサー", "sp": "メガホンレーザー5.1ch", "range": 3 },
  { "name": "ワイドローラーコラボ", "name_en": "Big Swig Roller Express", "class": "ローラー", "sub": "ラインマーカー", "sp": "アメフラシ", "range": 3 },
  { "name": "ヴァリアブルローラー", "name_en": "Flingza Roller", "class": "ローラー", "sub": "トラップ", "sp": "マルチミサイル", "range": 3 },
  { "name": "ワイドローラー惑", "name_en": "Foil Big Swig Roller", "class": "ローラー", "sub": "トーピード", "sp": "ウルトラハンコ", "range": 3 },
  { "name": "カーボンローラーデコ", "name_en": "Carbon Roller Deco", "class": "ローラー", "sub": "クイックボム", "sp": "ウルトラショット", "range": 1 },
  { "name": "カーボンローラーANGL", "name_en": "Annaki Carbon Roller", "class": "ローラー", "sub": "タンサンボム", "sp": "デコイチラシ", "range": 1 },
  { "name": "ヴァリアブルローラーフォイル", "name_en": "Foil Flingza Roller", "class": "ローラー", "sub": "キューバンボム", "sp": "スミナガシート", "range": 3 },
  { "name": "オーダーブラシレプリカ", "name_en": "Order Brush Replica", "class": "フデ", "sub": "キューバンボム", "sp": "ショクワンダー", "range": 1 },
  { "name": "ホクサイ", "name_en": "Octobrush", "class": "フデ", "sub": "キューバンボム", "sp": "ショクワンダー", "range": 1 },
  { "name": "パブロ", "name_en": "Inkbrush", "class": "フデ", "sub": "スプラッシュボム", "sp": "メガホンレーザー5.1ch", "range": 1 },
  { "name": "ホクサイ・ヒュー", "name_en": "Octobrush Nouveau", "class": "フデ", "sub": "ジャンプビーコン", "sp": "アメフラシ", "range": 1 },
  { "name": "ホクサイ彗", "name_en": "Kensa Octobrush", "class": "フデ", "sub": "ロボットボム", "sp": "テイオウイカ", "range": 1 },
  { "name": "フィンセント", "name_en": "Painbrush", "class": "フデ", "sub": "カーリングボム", "sp": "ホップソナー", "range": 2 },
  { "name": "パブロ・ヒュー", "name_en": "Inkbrush Nouveau", "class": "フデ", "sub": "トラップ", "sp": "ウルトラハンコ", "range": 1 },
  { "name": "フィンセント・ヒュー", "name_en": "Painbrush Nouveau", "class": "フデ", "sub": "ポイントセンサー", "sp": "マルチミサイル", "range": 2 },
  { "name": "フィンセントBRNZ", "name_en": "Bronze Painbrush", "class": "フデ", "sub": "スプラッシュシールド", "sp": "ウルトラショット", "range": 2 },
  { "name": "オーダースロッシャーレプリカ", "name_en": "Order Slosher Replica", "class": "スロッシャー", "sub": "スプラッシュボム", "sp": "トリプルトルネード", "range": 2 },
  { "name": "バケットスロッシャー", "name_en": "Slosher", "class": "スロッシャー", "sub": "スプラッシュボム", "sp": "トリプルトルネード", "range": 2 },
  { "name": "ヒッセン", "name_en": "Tri-Slosher", "class": "スロッシャー", "sub": "ポイズンミスト", "sp": "ジェットパック", "range": 1 },
  { "name": "バケットスロッシャーデコ", "name_en": "Slosher Deco", "class": "スロッシャー", "sub": "ラインマーカー", "sp": "ショクワンダー", "range": 2 },
  { "name": "スクリュースロッシャー", "name_en": "Sloshing Machine", "class": "スロッシャー", "sub": "タンサンボム", "sp": "ナイスダマ", "range": 3 },
  { "name": "モップリン", "name_en": "Dread Wringer", "class": "スロッシャー", "sub": "キューバンボム", "sp": "サメライド", "range": 3 },
  { "name": "ヒッセン・ヒュー", "name_en": "Tri-Slosher Nouveau", "class": "スロッシャー", "sub": "タンサンボム", "sp": "エナジースタンド", "range": 1 },
  { "name": "モップリンD", "name_en": "Dread Wringer D", "class": "スロッシャー", "sub": "ジャンプビーコン", "sp": "ホップソナー", "range": 3 },
  { "name": "ヒッセンASH", "name_en": "Annaki Tri-Slosher", "class": "スロッシャー", "sub": "スプラッシュボム", "sp": "スミナガシート", "range": 1 },
  { "name": "オーバーフロッシャー", "name_en": "Bloblobber", "class": "スロッシャー", "sub": "スプリンクラー", "sp": "アメフラシ", "range": 4 },
  { "name": "モップリン角", "name_en": "Kensa Dread Wringer", "class": "スロッシャー", "sub": "カーリングボム", "sp": "カニタンク", "range": 3 },
  { "name": "スクリュースロッシャーネオ", "name_en": "Sloshing Machine Neo", "class": "スロッシャー", "sub": "ポイントセンサー", "sp": "ウルトラショット", "range": 3 },
  { "name": "オーバーフロッシャーデコ", "name_en": "Bloblobber Deco", "class": "スロッシャー", "sub": "ラインマーカー", "sp": "テイオウイカ", "range": 4 },
  { "name": "エクスプロッシャー", "name_en": "Explosher", "class": "スロッシャー", "sub": "ポイントセンサー", "sp": "アメフラシ", "range": 5 },
  { "name": "エクスプロッシャーカスタム", "name_en": "Custom Explosher", "class": "スロッシャー", "sub": "スプラッシュシールド", "sp": "ウルトラチャクチ", "range": 5 },
  { "name": "オーダースピナーレプリカ", "name_en": "Order Splatling Replica", "class": "スピナー", "sub": "スプリンクラー", "sp": "ホップソナー", "range": 4 },
  { "name": "バレルスピナー", "name_en": "Heavy Splatling", "class": "スピナー", "sub": "スプリンクラー", "sp": "ホップソナー", "range": 4 },
  { "name": "スプラスピナー", "name_en": "Mini Splatling", "class": "スピナー", "sub": "クイックボム", "sp": "ウルトラハンコ", "range": 3 },
  { "name": "イグザミナー", "name_en": "Heavy Edit Splatling", "class": "スピナー", "sub": "カーリングボム", "sp": "エナジースタンド", "range": 4 },
  { "name": "バレルスピナーデコ", "name_en": "Heavy Splatling Deco", "class": "スピナー", "sub": "ポイントセンサー", "sp": "テイオウイカ", "range": 4 },
  { "name": "イグザミナー・ヒュー", "name_en": "Heavy Edit Splatling Nouveau", "class": "スピナー", "sub": "スプラッシュボム", "sp": "カニタンク", "range": 4 },
  { "name": "ハイドラント", "name_en": "Hydra Splatling", "class": "スピナー", "sub": "ロボットボム", "sp": "ナイスダマ", "range": 5 },
  { "name": "ハイドラントカスタム", "name_en": "Custom Hydra Splatling", "class": "スピナー", "sub": "トラップ", "sp": "スミナガシート", "range": 5 },
  { "name": "スプラスピナーコラボ", "name_en": "Zink Mini Splatling", "class": "スピナー", "sub": "ポイズンミスト", "sp": "グレートバリア", "range": 3 },
  { "name": "ハイドラント圧", "name_en": "Kensa Hydra Splatling", "class": "スピナー", "sub": "スプリンクラー", "sp": "グレートバリア", "range": 5 },
  { "name": "スプラスピナーPYTN", "name_en": "Kensa Mini Splatling", "class": "スピナー", "sub": "ジャンプビーコン", "sp": "ウルトラショット", "range": 3 },
  { "name": "ノーチラス79", "name_en": "Nautilus 79", "class": "スピナー", "sub": "キューバンボム", "sp": "ウルトラチャクチ", "range": 4 },
  { "name": "ノーチラス47", "name_en": "Nautilus 47", "class": "スピナー", "sub": "ポイントセンサー", "sp": "アメフラシ", "range": 4 },
  { "name": "クーゲルシュライバー・ヒュー", "name_en": "Ballpoint Splatling Nouveau", "class": "スピナー", "sub": "トラップ", "sp": "キューインキ", "range": 5 },
  { "name": "クーゲルシュライバー", "name_en": "Ballpoint Splatling", "class": "スピナー", "sub": "タンサンボム", "sp": "ジェットパック", "range": 5 },
  { "name": "オーダーマニューバーレプリカ", "name_en": "Order Dualie Replicas", "class": "マニューバー", "sub": "キューバンボム", "sp": "カニタンク", "range": 2 },
  { "name": "スプラマニューバー", "name_en": "Splat Dualies", "class": "マニューバー", "sub": "キューバンボム", "sp": "カニタンク", "range": 2 },
  { "name": "デュアルスイーパー", "name_en": "Dualie Squelchers", "class": "マニューバー", "sub": "スプラッシュボム", "sp": "ホップソナー", "range": 3 },
  { "name": "スプラマニューバーコラボ", "name_en": "Enperry Splat Dualies", "class": "マニューバー", "sub": "カーリングボム", "sp": "ウルトラチャクチ", "range": 2 },
  { "name": "スパッタリー", "name_en": "Dapple Dualies", "class": "マニューバー", "sub": "ジャンプビーコン", "sp": "エナジースタンド", "range": 1 },
  { "name": "スプラマニューバー耀", "name_en": "Kensa Splat Dualies", "class": "マニューバー", "sub": "タンサンボム", "sp": "グレートバリア", "range": 2 },
  { "name": "デュアルスイーパーカスタム", "name_en": "Custom Dualie Squelchers", "class": "マニューバー", "sub": "ジャンプビーコン", "sp": "デコイチラシ", "range": 3 },
  { "name": "クアッドホッパーブラック", "name_en": "Dark Tetra Dualies", "class": "マニューバー", "sub": "ロボットボム", "sp": "サメライド", "range": 2 },
  { "name": "デュアルスイーパー蹄", "name_en": "Annaki Dualie Squelchers", "class": "マニューバー", "sub": "ポイントセンサー", "sp": "スミナガシート", "range": 3 },
  { "name": "ケルビン525", "name_en": "Glooga Dualies", "class": "マニューバー", "sub": "スプラッシュシールド", "sp": "ナイスダマ", "range": 3 },
  { "name": "クアッドホッパーホワイト", "name_en": "Light Tetra Dualies", "class": "マニューバー", "sub": "スプリンクラー", "sp": "ショクワンダー", "range": 2 },
  { "name": "スパッタリー・ヒュー", "name_en": "Dapple Dualies Nouveau", "class": "マニューバー", "sub": "トーピード", "sp": "サメライド", "range": 1 },
  { "name": "ケルビン525デコ", "name_en": "Glooga Dualies Deco", "class": "マニューバー", "sub": "ポイントセンサー", "sp": "ウルトラショット", "range": 3 },
  { "name": "スパッタリーOWL", "name_en": "Annaki Dapple Dualies", "class": "マニューバー", "sub": "スプラッシュボム", "sp": "メガホンレーザー5.1ch", "range": 1 },
  { "name": "オーダーシェルターレプリカ", "name_en": "Order Brella Replica", "class": "シェルター", "sub": "スプリンクラー", "sp": "トリプルトルネード", "range": 2 },
  { "name": "パラシェルター", "name_en": "Splat Brella", "class": "シェルター", "sub": "スプリンクラー", "sp": "トリプルトルネード", "range": 2 },
  { "name": "24式張替傘・甲", "name_en": "Recycled Brella 24 Mk I", "class": "シェルター", "sub": "ラインマーカー", "sp": "グレートバリア", "range": 2 },
  { "name": "キャンピングシェルター", "name_en": "Tenta Brella", "class": "シェルター", "sub": "ジャンプビーコン", "sp": "キューインキ", "range": 1 },
  { "name": "スパイガジェット", "name_en": "Undercover Brella", "class": "シェルター", "sub": "トラップ", "sp": "サメライド", "range": 1 },
  { "name": "パラシェルターソレーラ", "name_en": "Sorella Brella", "class": "シェルター", "sub": "ロボットボム", "sp": "ジェットパック", "range": 2 },
  { "name": "24式張替傘・乙", "name_en": "Recycled Brella 24 Mk II", "class": "シェルター", "sub": "ポイズンミスト", "sp": "ウルトラチャクチ", "range": 2 },
  { "name": "キャンピングシェルターソレーラ", "name_en": "Tenta Sorella Brella", "class": "シェルター", "sub": "トラップ", "sp": "ウルトラショット", "range": 1 },
  { "name": "スパイガジェットソレーラ", "name_en": "Undercover Sorella Brella", "class": "シェルター", "sub": "トーピード", "sp": "スミナガシート", "range": 1 },
  { "name": "キャンピングシェルターCREM", "name_en": "Mint-Camo Tenta Brella", "class": "シェルター", "sub": "ポイズンミスト", "sp": "デコイチラシ", "range": 1 },
  { "name": "スパイガジェット繚", "name_en": "Kensa Undercover Brella", "class": "シェルター", "sub": "カーリングボム", "sp": "メガホンレーザー5.1ch", "range": 1 },
  { "name": "オーダーワイパーレプリカ", "name_en": "Order Splatana Replica", "class": "ワイパー", "sub": "クイックボム", "sp": "ショクワンダー", "range": 2 },
  { "name": "ドライブワイパー", "name_en": "Splatana Wiper", "class": "ワイパー", "sub": "トーピード", "sp": "ウルトラハンコ", "range": 2 },
  { "name": "ドライブワイパーデコ", "name_en": "Splatana Wiper Deco", "class": "ワイパー", "sub": "ジャンプビーコン", "sp": "マルチミサイル", "range": 2 },
  { "name": "ドライブワイパーRUST", "name_en": "Steel-Head Splatana Wiper", "class": "ワイパー", "sub": "カーリングボム", "sp": "ウルトラショット", "range": 2 },
  { "name": "ジムワイパー", "name_en": "Splatana Stamper", "class": "ワイパー", "sub": "クイックボム", "sp": "ショクワンダー", "range": 3 },
  { "name": "ジムワイパー・ヒュー", "name_en": "Splatana Stamper Nouveau", "class": "ワイパー", "sub": "ポイズンミスト", "sp": "カニタンク", "range": 3 },
  { "name": "デンタルワイパーミント", "name_en": "Mint Decavitator", "class": "ワイパー", "sub": "キューバンボム", "sp": "グレートバリア", "range": 3 },
  { "name": "ジムワイパー封", "name_en": "Kensa Splatana Stamper", "class": "ワイパー", "sub": "ロボットボム", "sp": "ナイスダマ", "range": 3 },
  { "name": "デンタルワイパースミ", "name_en": "Charcoal Decavitator", "class": "ワイパー", "sub": "スプラッシュシールド", "sp": "ジェットパック", "range": 3 },
  { "name": "オーダーストリンガーレプリカ", "name_en": "Order Stringer Replica", "class": "ストリンガー", "sub": "ポイズンミスト", "sp": "メガホンレーザー5.1ch", "range": 4 },
  { "name": "トライストリンガー", "name_en": "Tri-Stringer", "class": "ストリンガー", "sub": "ポイズンミスト", "sp": "メガホンレーザー5.1ch", "range": 4 },
  { "name": "LACT450", "name_en": "REEF-LUX 450", "class": "ストリンガー", "sub": "カーリングボム", "sp": "マルチミサイル", "range": 2 },
  { "name": "トライストリンガーコラボ", "name_en": "Inkline Tri-Stringer", "class": "ストリンガー", "sub": "スプリンクラー", "sp": "デコイチラシ", "range": 4 },
  { "name": "LACT-450デコ", "name_en": "REEF-LUX 450 Deco", "class": "ストリンガー", "sub": "スプラッシュシールド", "sp": "サメライド", "range": 2 },
  { "name": "トライストリンガー燈", "name_en": "Kensa Tri-Stringer", "class": "ストリンガー", "sub": "ラインマーカー", "sp": "ジェットパック", "range": 4 },
  { "name": "LACT-450MILK", "name_en": "Annaki REEF-LUX 450", "class": "ストリンガー", "sub": "トーピード", "sp": "ナイスダマ", "range": 2 },
  { "name": "フルイドV", "name_en": "Wellstring V", "class": "ストリンガー", "sub": "ロボットボム", "sp": "ウルトラハンコ", "range": 4 },
  { "name": "フルイドVカスタム", "name_en": "Custom Wellstring V", "class": "ストリンガー", "sub": "ポイントセンサー", "sp": "ホップソナー", "range": 4 }
];
