const translations = {
  ja: {
    'loading-data': 'ブキデータを読み込み中...',
    'or-divider': 'または',

    'restored-previous-data': '前回までのデータを復元しました',

    'restored-previous-data': '前回までのデータを復元しました',
    // Realtime
    'realtime-join-by-id-title': 'ルームIDで参加',
    'realtime-room-id-placeholder': '12桁のルームIDを入力',
    'realtime-player-name-placeholder': 'オンラインプレイで使う名前',
    'realtime-join-btn': '参加する',
    'realtime-leave-btn': '退出',
    'realtime-create-btn': '新しいルームを作成',
    'realtime-creating-btn': '作成中...',
    'realtime-joining-room': 'ルームに参加中...',
    'realtime-error-create': 'ルームの作成に失敗しました。',
    'realtime-error-join': 'ルームへの参加に失敗しました。',
    'realtime-room-id': 'ルームID:',
    'realtime-title': 'リアルタイム連携',
    'realtime-room-password': 'パスワード:',
    'realtime-host': 'ホスト',
    'realtime-leave-confirm': '本当にルームから退出しますか？',
    'realtime-error-connect': 'ルームに接続できませんでした。IDが正しいか確認してください。',
    'realtime-you': 'あなた',
    'realtime-reconnecting': 'サーバーに再接続しています...',
    'error-join-input-required': 'ルームIDとパスワードを入力してください。',
    'error-wrong-password': 'パスワードが違います。',
    'copied-room-id': 'ルームIDをコピーしました',
    'copied-room-password': 'パスワードをコピーしました',
    'realtime-copy-invite-link': '招待リンクをコピー',
    'copied-invite-link': '招待リンクをコピーしました！',
    'results-copied-to-clipboard': '抽選結果をクリップボードにコピーしました！',
    'copy-not-supported': 'お使いのブラウザではクリップボードへのコピーがサポートされていません。',
    'realtime-error-full': 'ルームが満員です。',
    'copy-failed': 'クリップボードへのコピーに失敗しました。',
    'realtime-autojoin-name-required': '自動参加するには、まずプレイヤー名を入力してください。',
    'firebase-not-configured': 'Firebaseが設定されていません。管理者に連絡してください。',
    'firebase-init-failed': 'サーバーへの接続初期化に失敗しました。ページをリロードしてください。',
    'battery-low-prevent-sleep': 'バッテリー残量が少ないため、スリープ防止を有効にできませんでした。',
    'realtime-error-banned-globally': 'あなたのアカウントは利用が制限されています。',
    'battery-charging-estimate': '満充電まで残り約{hours}時間{minutes}分',
    'battery-charging-estimate-calculating': '満充電までの推定時間を計算中...',
    'battery-not-charging': '充電していません',
    'system-room-dissolved-by-host': 'ホストが退出したため、ルームは解散しました。',
    'realtime-set-vc-link': 'VCリンク設定',
    'realtime-change-vc-link': 'VCリンク変更',
    'realtime-set-vc-link-prompt': 'ボイスチャットの招待リンク(Discordのみ)を入力してください。\n空欄で送信するとリンクが削除されます。',
    'realtime-set-vc-link-success': 'VCリンクを設定しました。',
    'realtime-set-vc-link-removed': 'VCリンクを削除しました。',
    'realtime-set-vc-link-fail': 'VCリンクの設定に失敗しました。',
    'realtime-set-vc-link-invalid': '無効なURLです。`https://discord.gg/` から始まるDiscordの招待リンクを入力してください。',
    'realtime-join-vc': 'VCに参加',
    'unbanned-reload-notification': 'BANが解除されました。5秒後にページをリロードして、全ての機能を有効にします。',
    'realtime-error-join-no-id': 'ルームIDを入力してください。',
    'realtime-password-required': 'パスワードを入力してください。',
    'announcement-prefix': 'お知らせ',
    'public-rooms-list-title': '公開中のルームリスト',
    'public-rooms-list-empty': '現在、参加可能なルームはありません。',
    'password-protected-room': 'このルームはパスワードで保護されています。',
    'room-full': '満員',
    'admin-room-host': 'ホスト',
    'admin-room-players': '人数',
    'admin-room-actions': '操作',
    'realtime-create-title': '新しいルームを作成',
    'realtime-room-visibility': '公開範囲',
    'realtime-set-password': 'パスワードを設定',
    'realtime-password-placeholder': 'パスワード',

    // Header & Controls
    'app-title': 'スプラトゥーン3｜ブキルーレット',
    'spin': '回す',
    'spin-next': '次の抽選へ',
    'reset': 'リセット',
    'player-count': 'プレイヤー数',
    'no-repeat': 'ブキ重複なし',
    'no-repeat-title': '有効にすると、一度出たブキは履歴をリセットするまで抽選対象から除外されます。',
    'fullscreen': '全画面表示',
    'exit-fullscreen': '全画面表示を終了',
    'fullscreen-toggle': '全画面表示切り替え',
    'settings': '設定',
    'invite-button': '招待',
    // Team Splitter
    'team-splitter-title': 'チーム分け',
    'team-splitter-button': 'チーム分け',
    'team-splitter-num-teams': 'チーム数',
    'team-splitter-players-label': 'プレイヤーリスト',
    'team-splitter-players-placeholder': 'プレイヤー名を1行に1人ずつ入力してください。\n(オンラインルームでは自動入力されます)',
    'team-splitter-shuffle-btn': 'マッチング開始',
    'team-splitter-balance-by-range': 'ブキ射程でバランス調整',
    'team-splitter-copy-btn': '結果をコピー',
    'team-splitter-team-name': 'チーム {name}',
    'team-splitter-no-players': 'プレイヤーを2人以上入力してください。',
    'team-splitter-results-copied': 'チーム分け結果をクリップボードにコピーしました。',
    'team-alpha': 'アルファ',
    'team-bravo': 'ブラボー',
    'team-charlie': 'チャーリー',
    'team-delta': 'デルタ',
    'team-splitter-matching': 'マッチング中...',

    // Player Settings
    'player-settings-title': 'プレイヤー設定',
    'player-settings-confirm': '決定',
    'player-id-label': 'あなたのプレイヤーID',
    'player-settings-updating': 'プレイヤー情報を更新中...',
    'player-bio-label': '自己紹介',
    'player-bio-placeholder': 'よろしくお願いします！(最大100文字)',
    'player-favorite-weapon-label': '好きなブキ',
    'player-favorite-weapon-none': '選択しない',
    'player-profile-tooltip': '{name}\n―――――\n好きなブキ: {favoriteWeapon}\n\n{bio}',
    'player-bio-empty': '(自己紹介がありません)',
    'player-favorite-weapon-empty': '未設定',
    'player-settings-updated': 'プレイヤー情報を更新しました',
    'player-settings-update-failed': 'プレイヤー情報の更新に失敗しました',

    // Main Display
    'reset-display-name': '準備OK！',
    'reset-display-class': 'プレイヤー数を選択して「回す」を押してください',
    'current-candidates': '現在 {n}種類のブキから抽選 (確率: {prob}%)',
    'no-candidates-filter': 'フィルター条件に合うブキがありません',
    'player-draw': '{playerNum}人目の抽選',
    'player-draw-wait': '待機中...',
    'player-result-list': 'P{i}',
    'player-name-modal-title': 'プレイヤー名入力',
    'player-name-modal-help': '各プレイヤーの名前を入力してください。',
    'player-name-modal-start-btn': '抽選開始',
    'player-name-input-label': 'プレイヤー {i}',

    // Alerts & Errors
    'no-candidates-alert': '重複なしモードですが、抽選対象のブキが{poolCount}種類しかなく、プレイヤー数({playerCount}人)に足りません。',
    'no-candidates-alert-title': '抽選対象のブキがありません。フィルター設定を確認してください。',
    'error': 'エラー',
    'player-name-required': 'オンライン機能を利用するにはプレイヤー名を入力してください。',
    'error-failed-draw': '抽選に失敗しました。',
    'error-loading-weapons': 'ブキデータの読み込みに失敗しました。',
    'db-not-connected-error': 'データベースに接続されていません。ページの読み込み時にエラーが発生した可能性があります。',
    'realtime-error-banned': 'あなたはこのルームへの参加が禁止されています。',
    'realtime-error-blocked': 'あなたはこのルームへの参加がブロックされています。',
    // Filters
    'filter-title': 'ブキ絞り込み',
    'filter-class': 'ブキ種',
    'filter-sub': 'サブウェポン',
    'filter-special': 'スペシャルウェポン',
    'filter-toggle': 'すべて切り替え',
    'filter-toggle-all-help': 'クリックして全て選択/解除',
    'filter-collection': 'コレクション',

    // Histocollection': 'コレクション',

    // History
    'history-title': '抽選履歴',
    'history-count-value': '{batches}回 ({total}ブキ)',
    'history-empty': 'まだ履歴がありません',
    'history-delete-item': 'この項目を削除',
    'history-copy-result': 'この結果をコピー',
    'history-copy-item': 'このブキをコピー',
    'history-clear-search': '日付フィルターをクリア',

    // Player List & Chat
    'player-list-title': '参加者',
    'player-list-count': '{count}人',
    'player-list-empty': '参加者がいません',
    'chat-title': 'チャット',
    'chat-placeholder': 'メッセージを入力',
    'chat-send-btn': '送信',
    'chat-mention-tooltip': '{name}さんをメンションする',
    'chat-send-fail': 'メッセージの送信に失敗しました。',
    'player-muted-indicator': 'ミュート中',
    'chat-error-muted': 'ミュートされています。解除時刻: {time}',
    'chat-voice-input-start': '音声入力を開始',
    'chat-voice-input-stop': '音声入力を停止',
    'chat-voice-error-permission': 'マイクへのアクセスが許可されていません。',
    'chat-voice-error-no-speech': '音声が認識されませんでした。もう一度お試しください。',
    'chat-voice-error-unknown': '音声入力で不明なエラーが発生しました。',
    'report-button-title': '{name}さんを通報する',
    'report-modal-title': 'プレイヤーを報告',
    'report-modal-target': '報告対象:',
    'report-modal-reason': '報告理由',
    'report-modal-reason-placeholder': '不適切な名前、チャットでの暴言、嫌がらせ行為など、具体的な理由を記入してください。',
    'report-modal-submit': '報告を送信',
    'report-modal-submitted': '報告を送信しました。ご協力ありがとうございます。',
    'report-modal-submit-error': '報告の送信に失敗しました。時間をおいて再度お試しください。',

    'realtime-admin-menu': '管理メニュー',
    'realtime-kick-player': 'キック',
    'realtime-block-player': '名前でブロック',
    'realtime-ban-player': 'BAN',
    'realtime-kick-confirm': '{name}さんをルームからキックしますか？',
    'realtime-block-confirm': '{name}さんをブロックリストに追加し、ルームからキックしますか？同じ名前のプレイヤーは再参加できなくなります。',
    'realtime-ban-confirm': '{name}さんをBANし、ルームからキックしますか？このユーザーはオンライン機能が利用できなくなります。',

    // System Messages
    'system-new-host': '[サーバー] {name}さんが新しいホストになりました。',
    'system-player-joined': '[サーバー] {name}さんが参加しました。',
    'system-player-left': '[サーバー] {name}さんが退出しました。',
    'system-player-kicked': '[サーバー] {name}さんが{host}によってキックされました。',
    'system-player-blocked': '[サーバー] {name}さんが{host}によってブロックされました。',
    'system-player-banned': '[サーバー] {name}さんが{host}によってBANされました。',
    'system-you-were-kicked': '{host}によってルームからキックされました。',
    'system-you-were-banned': '{host}によってルームからBANされました。',
    'system-you-were-warned-title': '管理者からの警告',
    'toast-setting-on': '{settingName}をオンにしました',
    'toast-setting-off': '{settingName}をオフにしました',
    'toast-player-joined': '{name}さんが参加しました',
    'toast-player-left': '{name}さんが退出しました',

    // Mute System Messages
    'system-player-muted': '[サーバー] {name}さんが{admin}によって{duration}分間ミュートされました。',
    'system-player-unmuted': '[サーバー] {name}さんのミュートが解除されました。',

    // Probability Table
    'prob-title': '各ブキの排出確率',
    'prob-no-candidates': '対象ブキなし',
    'prob-weapon-name': 'ブキ名',
    'prob-class': 'ブキ種',
    'prob-sub': 'サブ',
    'prob-special': 'スペシャル',
    'prob-value': '確率',
    'prob-total': '合計',

    // Settings Modal
    'settings-title': '設定',
    'settings-close': '設定を閉じる',

    // General Settings
    'settings-general-title': '一般設定',
    'settings-auto-copy': '結果をクリップボードに自動コピー',
    'settings-auto-copy-help': '抽選完了後、結果をテキスト形式でクリップボードにコピーします。',
    'settings-prevent-sleep': 'スリープを防止',
    'settings-prevent-sleep-help': 'このページを開いている間、デバイスがスリープモードになるのを防ぎます。',
    'wake-lock-acquired': 'スリープ防止が有効になりました。',
    'wake-lock-failed': 'スリープ防止を有効にできませんでした。',
    'settings-theme': 'テーマ',
    'settings-theme-light': 'ライト',
    'settings-theme-dark': 'ダーク',
    'settings-theme-system': 'システム',
    'settings-language': '言語',
    'settings-language-ja': '日本語', // この行は変更ありません
    'settings-language-en': 'English', // この行は変更ありません
    'settings-reset-data-confirm': '本当にすべてのデータを削除しますか？\nこの操作は元に戻すことができず、ページがリロードされます。',

    // Presets
    'settings-presets-title': 'プリセット',
    'settings-presets-save-current': '現在のフィルターを保存',
    'settings-presets-save-placeholder': 'プリセット名',
    'settings-presets-save-btn': '保存',
    'settings-presets-load-btn': '読込',
    'settings-presets-delete-btn': '削除',
    'settings-presets-copy-btn': 'コピーを保存',
    'settings-presets-delete-confirm': 'プリセット「{name}」を削除しますか？',
    'settings-presets-saved': 'プリセット「{name}」を保存しました。',
    'settings-presets-loaded': 'プリセット「{name}」を読み込みました。',
    // Custom Pool
    'custom-pool-btn': 'カスタムプール',
    'custom-pool-title': 'カスタムプール設定',
    'custom-pool-enable': 'カスタムプールを有効にする',
    'custom-pool-desc': '有効にすると、ここで選択したブキのみが抽選対象になります。無効にすると、通常のフィルター設定が使用されます。',
    'custom-pool-weapon-list': 'ブキリスト',
    // Footer
    'footer-text': 'このツールは<a href="https://github.com/Yasaitachi/Splatoon3-WeaponRoulette-Online" target="_blank" class="link">GitHub</a>で無料で公開しています。バグ報告や機能の要望は<a href="https://discord.gg/ShjRzZ7FBa" target="_blank" class="link">サポートサーバー</a>まで。',

    // Admin Dashboard
    'admin-dashboard-title': '管理者ダッシュボード',
    'admin-back-to-app': 'アプリに戻る',
    'admin-auth-failed': 'このページにアクセスする権限がありません。',
    'admin-summary-title': '概要',
    'admin-summary-active-rooms': 'アクティブなルーム数',
    'admin-summary-total-users': '総ユーザー数',
    'admin-summary-new-reports': '新規通報',
    'admin-rooms-title': 'アクティブなルーム',
    'admin-room-id': 'ルームID',
    'admin-room-host': 'ホスト',
    'admin-room-players': '人数',
    'admin-room-visibility': '公開範囲',
    'admin-room-public': '公開',
    'admin-room-private': '非公開',
    'admin-room-friends': 'フレンド',
    'admin-room-time-left': '残り時間',
    'admin-room-created-at': '作成日時',
    'admin-room-actions': '操作',
    'admin-dissolve-room': '強制解散',
    'admin-dissolve-confirm': 'ルーム {roomId} を強制的に解散します。よろしいですか？',
    'admin-dissolve-success': 'ルーム {roomId} を解散しました。',
    'admin-dissolve-fail': 'ルーム {roomId} の解散に失敗しました。',
    'admin-reports-title': '通報管理',
    'admin-report-time': '日時',
    'admin-report-reporter': '報告者',
    'admin-report-reported': '対象者',
    'admin-report-reason': '理由',
    'admin-report-status': 'ステータス',
    'admin-report-actions': '操作',
    'admin-mark-reviewed': '確認済みにする',
    'admin-report-marked-success': '通報を確認済みにしました。',
    'admin-report-marked-fail': '通報の更新に失敗しました。',
    'admin-users-title': 'ユーザー管理',
    'admin-user-search-label': 'ユーザー検索 (名前 or ID)',
    'admin-user-search-placeholder': '名前、永続ID、または #付きのShortID',
    'admin-user-search-btn': '検索',
    'admin-user-search-min-length': '検索するには2文字以上入力してください。',
    'admin-user-search-fail': 'ユーザー検索に失敗しました。',
    'admin-searching': '検索中...',
    'pagination-prev': '前へ',
    'pagination-next': '次へ',
    'admin-user-not-found': 'ユーザーが見つかりません。',
    'admin-user-id': '永続ID',
    'admin-user-name': '名前',
    'admin-user-shortid': 'ShortID',
    'admin-user-status': '状態',
    'admin-user-created-at': '作成日時',
    'admin-user-last-activity': '最終アクティビティ',
    'admin-user-actions': '操作',
    'admin-user-banned': 'BAN',
    'admin-user-status-online': 'オンライン',
    'admin-user-status-offline': 'オフライン',
    'admin-user-status-banned': 'BAN',
    'admin-user-active': 'アクティブ',
    'admin-unban-user': 'BAN解除',
    'admin-mute-user': 'グローバルミュート',
    'admin-user-banned-success': '{name} をBANしました。',
    'admin-user-banned-fail': '{name} のBANに失敗しました。',
    'admin-unban-confirm': 'ユーザー {userId} のBANを解除しますか？',
    'admin-user-unbanned-success': 'ユーザー {userId} のBANを解除しました。',
    'admin-user-unbanned-fail': 'ユーザー {userId} のBAN解除に失敗しました。',
    'admin-mute-prompt': '{name} をミュートする期間（分）を入力してください。',
    'admin-mute-invalid-duration': '無効な期間です。正の数値を入力してください。',
    'admin-user-muted-success': '{name} を {duration} 分間ミュートしました。',
    'admin-user-muted-fail': '{name} のミュートに失敗しました。',
    'admin-announcement-title': 'お知らせ投稿',
    'admin-announcement-message': 'メッセージ',
    'admin-announcement-level': 'レベル',
    'admin-announcement-level-info': '情報',
    'admin-announcement-level-warning': '警告',
    'admin-announcement-level-error': '重要',
    'admin-announcement-post-btn': '投稿',
    'admin-announcement-empty': 'メッセージを入力してください。',
    'admin-announcement-success': 'お知らせを投稿しました。',
    'admin-announcement-fail': 'お知らせの投稿に失敗しました。',
    'admin-no-data': 'データがありません。',
    'admin-view-chat': 'チャット閲覧',
    'admin-chat-viewer-title': 'チャットログ',
    'admin-no-chat-history': 'このルームにはチャット履歴がありません。',
    'admin-chat-load-fail': 'チャットログの読み込みに失敗しました。',

    // Credits
    'credits-title': 'クレジット',
    'credits-font-heading': '見出しフォント',
    'credits-font-body': '本文フォント',

    // Update Notes
    'update-notes-title': 'バージョン {version} の新機能',
    'update-notes-close': '閉じる',
    'update-notes-v1.1.0': `
    * **UIデザインの刷新**: 全体的なレイアウト、配色、角の丸みや影などを調整し、よりモダンで洗練された外観にしました。
    * **フィルター機能の強化**: 各フィルターグループ（ブキ種、サブ、スペシャル）に「すべて選択/解除」ボタンを追加し、一括操作を可能にしました。
    * **操作性の向上**: ルーレット回転中に他の操作ができないことを視覚的に分かりやすくするため、操作不能なボタンが半透明になるようにしました。
    * **フィルターの折りたたみ**: 各フィルターグループを折りたためるようにし、画面をすっきりと使えるようになりました。この状態は記憶されます。
    * **※これまで使用されていた保存データは不具合が生じる可能性があるため、リセットされました。** *
    `,
    'update-notes-v1.2.5': `
    * **全画面表示の強化**: 全画面表示時に、日付、時刻（秒表示対応）、再生中のメディア情報、ネットワーク状況、バッテリー残量などの情報をステータスバーに表示できるようになりました。
    * **ステータスバーのカスタマイズ**: 設定画面から、ステータスバーに表示する各情報のオン/オフを切り替えられるようになりました。
    * **レイアウト調整**: 全画面表示のステータスバーのレイアウトを調整し、各情報が均等に配置されるようにしました。
    * **その他**:
    *   日付に曜日が表示されるようになりました。
    *   時計の秒表示の点滅オプションを調整しました。
    `,
  },
    en: {
    'loading-data': 'Loading weapon data...',
    'or-divider': 'or',

    'restored-previous-data': 'Restored previous session data',

    'restored-previous-data': 'Restored previous session data',
    // Realtime
    'realtime-join-by-id-title': 'Join by Room ID',
    'realtime-room-id-placeholder': 'Enter 12-digit Room ID',
    'realtime-host': 'Host',
    'realtime-leave-confirm': 'Are you sure you want to leave the room?',
    'realtime-error-connect': 'Could not connect to the room. Please check if the ID is correct.',
    'realtime-you': 'You',
    'realtime-reconnecting': 'Reconnecting to the server...',
    'copied-room-id': 'Room ID copied',
    'copied-room-password': 'Password copied',
    'realtime-copy-invite-link': 'Copy Invite Link',
    'realtime-title': 'Real-time Sync',
    'realtime-player-name-placeholder': 'Name used for online play',
    'realtime-join-btn': 'Join',
    'realtime-leave-btn': 'Leave Room',
    'realtime-create-btn': 'Create Room',
    'realtime-creating-btn': 'Creating...',
    'realtime-joining-room': 'Joining room...',
    'realtime-error-create': 'Failed to create room.',
    'realtime-error-join': 'Failed to join room.',
    'realtime-room-id': 'Room ID:',
    'realtime-room-password': 'Password:',
    'copied-invite-link': 'Invite link copied!',
    'results-copied-to-clipboard': 'Roulette results copied to clipboard!',
    'copy-not-supported': 'Clipboard copy not supported by your browser.',
    'realtime-error-full': 'The room is full.',
    'copy-failed': 'Failed to copy to clipboard.',
    'realtime-autojoin-name-required': 'To auto-join, please enter your player name first.',
    'firebase-not-configured': 'Firebase is not configured. Please contact the administrator.',
    'firebase-init-failed': 'Failed to initialize connection to the server. Please reload the page.',
    'battery-low-prevent-sleep': 'Could not enable sleep prevention due to low battery.',
    'realtime-error-banned-globally': 'Your account has been restricted.',
    'battery-charging-estimate': 'Approx. {hours}h {minutes}m to full charge',
    'battery-charging-estimate-calculating': 'Calculating estimated time to full charge...',
    'battery-not-charging': 'Not charging',
    'system-room-dissolved-by-host': 'The room was dissolved because the host left.',
    'realtime-set-vc-link': 'Set VC Link',
    'realtime-change-vc-link': 'Change VC Link',
    'realtime-set-vc-link-prompt': 'Enter the Discord invite link (URL).\nLeave blank to remove the link.',
    'realtime-set-vc-link-success': 'VC link has been set.',
    'realtime-set-vc-link-removed': 'VC link has been removed.',
    'realtime-set-vc-link-fail': 'Failed to set VC link.',
    'realtime-set-vc-link-invalid': 'Invalid URL. Please enter a Discord invite link starting with `https://discord.gg/`.',
    'realtime-join-vc': 'Join VC',
    'announcement-prefix': 'Announcement',
    'realtime-error-join-no-id': 'Please enter a Room ID.',
    'realtime-password-required': 'Please enter a password.',
    'public-rooms-list-title': 'Public Room List',
    'public-rooms-list-empty': 'There are no available rooms right now.',
    'password-protected-room': 'This room is password protected.',
    'room-full': 'Full',
    'admin-room-host': 'Host',
    'admin-room-players': 'Players',
    'admin-room-actions': 'Actions',
    'realtime-create-title': 'Create New Room',
    'realtime-room-visibility': 'Visibility',
    'realtime-set-password': 'Set Password',
    'realtime-password-placeholder': 'Password',
    'realtime-password-prompt': 'Please enter the password for this room:',
    'unbanned-reload-notification': 'Your ban has been lifted. The page will reload in 5 seconds to enable all features.',

    // Header & Controls
    'app-title': 'Splatoon 3 Weapon Roulette',
    'spin': 'Spin',
    'spin-next': 'Spin Next',
    'reset': 'Reset',
    'player-count': 'Players',
    'no-repeat': 'No Duplicates', // 変更なし
    'no-repeat-title': 'When enabled, drawn weapons are excluded from the pool until the history is reset.',
    'fullscreen': 'Fullscreen',
    'exit-fullscreen': 'Exit Fullscreen',
    'fullscreen-toggle': 'Toggle Fullscreen',
    'settings': 'Settings',
    'invite-button': 'Invite',
    // Team Splitter
    'team-splitter-title': 'Team Splitter',
    'team-splitter-button': 'Team Split',
    'team-splitter-num-teams': 'Number of Teams',
    'team-splitter-players-label': 'Player List',
    'team-splitter-players-placeholder': 'Enter player names, one per line.\n(Auto-filled in online rooms)',
    'team-splitter-shuffle-btn': 'Start Matching',
    'team-splitter-balance-by-range': 'Balance by Weapon Range',
    'team-splitter-copy-btn': 'Copy Results',
    'team-splitter-team-name': '{name} Team',
    'team-splitter-no-players': 'Please enter at least 2 players.',
    'team-splitter-results-copied': 'Team results copied to clipboard.',
    'team-alpha': 'Alpha',
    'team-bravo': 'Bravo',
    'team-charlie': 'Charlie',
    'team-delta': 'Delta',
    'team-splitter-matching': 'Matching...',

    // Player Settings
    'player-settings-title': 'Player Settings',
    'player-settings-confirm': 'Confirm',
    'player-id-label': 'Your Player ID',
    'player-settings-updating': 'Updating player info...',
    'player-bio-label': 'Bio',
    'player-bio-placeholder': 'Nice to meet you! (Max 100 chars)',
    'player-favorite-weapon-label': 'Favorite Weapon',
    'player-favorite-weapon-none': 'Not selected',
    'player-profile-tooltip': '{name}\n―――――\nFavorite: {favoriteWeapon}\n\n{bio}',
    'player-bio-empty': '(No bio provided)',
    'player-favorite-weapon-empty': 'Not set',
    'player-settings-updated': 'Player info updated',
    'player-settings-update-failed': 'Failed to update player info',

    // Main Display
    'reset-display-name': 'Ready!',
    'reset-display-class': 'Select number of players and press "Spin"',
    'current-candidates': '{n} weapons in pool (Prob: {prob}%)',
    'no-candidates-filter': 'No weapons match the filter criteria',
    'player-draw': 'Drawing for Player {playerNum}',
    'player-draw-wait': 'Waiting...',
    'player-result-list': 'P{i}',
    'player-name-modal-title': 'Enter Player Names',
    'player-name-modal-help': 'Please enter the name for each player.',
    'player-name-modal-start-btn': 'Start Roulette',
    'player-name-input-label': 'Player {i}',

    // Alerts & Errors
    'no-candidates-alert': 'No-duplicate mode is on, but the pool only has {poolCount} weapon(s), which is not enough for {playerCount} player(s).',
    'no-candidates-alert-title': 'There are no weapons to draw from. Please check your filter settings.',
    'error': 'Error',
    'player-name-required': 'Please enter a player name to use online features.',
    'error-failed-draw': 'Failed to draw a weapon.',
    'error-loading-weapons': 'Failed to load weapon data.',
    'error-join-input-required': 'Please enter Room ID and Password.',
    'error-wrong-password': 'Incorrect password.',
    'db-not-connected-error': 'Not connected to the database. An error may have occurred on page load.',
    'realtime-error-banned': 'You are banned from this room.',
    'realtime-error-blocked': 'You are blocked from this room.',
    // Filters
    'filter-title': 'Filter Weapons',
    'filter-class': 'Class',
    'filter-sub': 'Sub Weapon',
    'filter-special': 'Special Weapon',
    'filter-toggle': 'Toggle All',

    // History
    'history-title': 'Draw History',    'filter-toggle-all-help': 'Click to select/deselect all',
    'filter-collection': 'Collection',

    // History
    'history-title': 'Draw History',
    'history-count-value': '{batches} draws ({total} weapons)',
    'history-empty': 'No history yet',
    'history-delete-item': 'Delete this item',
    'history-copy-result': 'Copy this result',
    'history-copy-item': 'Copy this weapon',
    'history-clear-search': 'Clear date filter',

    // Player List & Chat
    'player-list-title': 'Participants',
    'player-list-count': '{count} players',
    'player-list-empty': 'No one is in the room yet.',
    'chat-title': 'Chat',
    'chat-placeholder': 'Type a message',
    'chat-send-btn': 'Send',
    'chat-mention-tooltip': 'Mention {name}',
    'chat-send-fail': 'Failed to send message.',
    'player-muted-indicator': 'Muted',
    'chat-error-muted': 'You are muted. Ends at: {time}',
    'chat-voice-input-start': 'Start voice input',
    'chat-voice-input-stop': 'Stop voice input',
    'chat-voice-error-permission': 'Microphone access was not permitted.',
    'chat-voice-error-no-speech': 'No speech was detected. Please try again.',
    'chat-voice-error-unknown': 'An unknown error occurred during voice input.',
    'report-button-title': 'Report {name}',
    'report-modal-title': 'Report Player',
    'report-modal-target': 'Reporting:',
    'report-modal-reason': 'Reason for Report',
    'report-modal-reason-placeholder': 'Please provide specific details, such as inappropriate name, abusive chat, harassment, etc.',
    'report-modal-submit': 'Submit Report',
    'report-modal-submitted': 'Report submitted. Thank you for your cooperation.',
    'report-modal-submit-error': 'Failed to submit report. Please try again later.',

    'realtime-admin-menu': 'Admin Menu',
    'realtime-kick-player': 'Kick',
    'realtime-block-player': 'Block Name',
    'realtime-ban-player': 'Ban',
    'realtime-kick-confirm': 'Are you sure you want to kick {name} from the room?',
    'realtime-block-confirm': 'Are you sure you want to block and kick {name}? Players with the same name cannot rejoin.',
    'realtime-ban-confirm': 'Are you sure you want to ban and kick {name}? This user will be restricted from all online features.',

    // System Messages
    'system-new-host': '[Server] {name} is the new host.',
    'system-player-joined': '[Server] {name} has joined.',
    'system-player-left': '[Server] {name} has left.',
    'system-player-kicked': '[Server] {name} was kicked by {host}.',
    'system-player-blocked': '[Server] {name} was blocked by {host}.',
    'system-player-banned': '[Server] {name} was banned by {host}.',
    'system-you-were-kicked': 'You were kicked from the room by {host}.',
    'system-you-were-banned': 'You were banned from the room by {host}.',
    'system-you-were-warned-title': 'Warning from Admin',
    'toast-setting-on': 'Enabled {settingName}',
    'toast-setting-off': 'Disabled {settingName}',
    'toast-player-joined': '{name} has joined',
    'toast-player-left': '{name} has left',

    // Mute System Messages
    'system-player-muted': '[Server] {name} was muted for {duration} minutes by {admin}.',
    'system-player-unmuted': '[Server] {name} has been unmuted.',

    // Probability Table
    'prob-title': 'Probability of each weapon',
    'prob-no-candidates': 'No candidates',
    'prob-weapon-name': 'Weapon',
    'prob-class': 'Class',
    'prob-sub': 'Sub',
    'prob-special': 'Special',
    'prob-value': 'Prob.',
    'prob-total': 'Total',

    // Settings Modal
    'settings-title': 'Settings',
    'settings-close': 'Close settings',

    // General Settings
    'settings-general-title': 'General Settings',
    'settings-auto-copy': 'Auto-copy result to clipboard',
    'settings-auto-copy-help': 'After a draw is complete, automatically copy the result as text to the clipboard.',
    'settings-prevent-sleep': 'Prevent Sleep',
    'settings-prevent-sleep-help': 'Prevents the device from going to sleep while this page is open.',
    'wake-lock-acquired': 'Wake Lock activated.',
    'wake-lock-failed': 'Failed to activate Wake Lock.',
    'settings-theme': 'Theme',
    'settings-theme-light': 'Light',
    'settings-theme-dark': 'Dark',
    'settings-theme-system': 'System',
    'settings-language': 'Language',
    'settings-language-ja': '日本語', // この行は変更ありません
    'settings-language-en': 'English', // この行は変更ありません
    'settings-reset-data-confirm': 'Are you sure you want to delete all data?\nThis action cannot be undone and the page will reload.',

    // Presets
    'settings-presets-title': 'Presets',
    'settings-presets-save-current': 'Save Current Filters',
    'settings-presets-save-placeholder': 'Preset name',
    'settings-presets-save-btn': 'Save',
    'settings-presets-load-btn': 'Load',
    'settings-presets-delete-btn': 'Delete',
    'settings-presets-copy-btn': 'Save a Copy',
    'settings-presets-delete-confirm': 'Are you sure you want to delete the preset "{name}"?',
    'settings-presets-saved': 'Preset "{name}" saved.',
    'settings-presets-loaded': 'Preset "{name}" loaded.',
    // Custom Pool
    'custom-pool-btn': 'Custom Pool',
    'custom-pool-title': 'Custom Pool Settings',
    'custom-pool-enable': 'Enable Custom Pool',
    'custom-pool-desc': 'When enabled, only the weapons selected here will be in the roulette. When disabled, the standard filter settings will be used.',
    'custom-pool-weapon-list': 'Weapon List',
    // Footer
    'footer-text': 'This tool is open source on <a href="https://github.com/Yasaitachi/Splatoon3-WeaponRoulette-Online" target="_blank" class="link">GitHub</a>. For bug reports or feature requests, join our <a href="https://discord.gg/ShjRzZ7FBa" target="_blank" class="link">Support Server</a>.',

    // Admin Dashboard
    'admin-dashboard-title': 'Admin Dashboard',
    'admin-back-to-app': 'Back to App',
    'admin-auth-failed': 'You do not have permission to access this page.',
    'admin-summary-title': 'Summary',
    'admin-summary-active-rooms': 'Active Rooms',
    'admin-summary-total-users': 'Total Users',
    'admin-summary-new-reports': 'New Reports',
    'admin-rooms-title': 'Active Rooms',
    'admin-room-id': 'Room ID',
    'admin-room-host': 'Host',
    'admin-room-players': 'Players',
    'admin-room-visibility': 'Visibility',
    'admin-room-public': 'Public',
    'admin-room-private': 'Private',
    'admin-room-friends': 'Friends',
    'admin-room-time-left': 'Time Left',
    'admin-room-created-at': 'Created At',
    'admin-room-actions': 'Actions',
    'admin-dissolve-room': 'Dissolve Room',
    'admin-dissolve-confirm': 'Are you sure you want to dissolve room {roomId}?',
    'admin-dissolve-success': 'Room {roomId} has been dissolved.',
    'admin-dissolve-fail': 'Failed to dissolve room {roomId}.',
    'admin-reports-title': 'Reports',
    'admin-report-time': 'Time',
    'admin-report-reporter': 'Reporter',
    'admin-report-reported': 'Reported',
    'admin-report-reason': 'Reason',
    'admin-report-status': 'Status',
    'admin-report-actions': 'Actions',
    'admin-mark-reviewed': 'Mark as Reviewed',
    'admin-report-marked-success': 'Report marked as reviewed.',
    'admin-report-marked-fail': 'Failed to update report status.',
    'admin-users-title': 'User Management',
    'admin-user-search-label': 'Search User (Name or ID)',
    'admin-user-search-placeholder': 'Name, Persistent ID, or ShortID with #',
    'admin-user-search-btn': 'Search',
    'admin-user-search-min-length': 'Please enter at least 2 characters to search.',
    'admin-user-search-fail': 'User search failed.',
    'admin-searching': 'Searching...',
    'pagination-prev': 'Prev',
    'pagination-next': 'Next',
    'admin-user-not-found': 'User not found.',
    'admin-user-id': 'Persistent ID',
    'admin-user-name': 'Name',
    'admin-user-shortid': 'ShortID',
    'admin-user-status': 'Status',
    'admin-user-created-at': 'Created At',
    'admin-user-last-activity': 'Last Activity',
    'admin-user-actions': 'Actions',
    'admin-user-banned': 'Banned',
    'admin-user-status-online': 'Online',
    'admin-user-status-offline': 'Offline',
    'admin-user-status-banned': 'Banned',
    'admin-user-active': 'Active',
    'admin-unban-user': 'Unban',
    'admin-mute-user': 'Global Mute',
    'admin-user-banned-success': 'Banned user {name}.',
    'admin-user-banned-fail': 'Failed to ban user {name}.',
    'admin-unban-confirm': 'Are you sure you want to unban user {userId}?',
    'admin-user-unbanned-success': 'Unbanned user {userId}.',
    'admin-user-unbanned-fail': 'Failed to unban user {userId}.',
    'admin-mute-prompt': 'Enter mute duration in minutes for {name}.',
    'admin-mute-invalid-duration': 'Invalid duration. Please enter a positive number.',
    'admin-user-muted-success': 'Muted {name} for {duration} minutes.',
    'admin-user-muted-fail': 'Failed to mute {name}.',
    'admin-announcement-title': 'Post Announcement',
    'admin-announcement-message': 'Message',
    'admin-announcement-level': 'Level',
    'admin-announcement-level-info': 'Info',
    'admin-announcement-level-warning': 'Warning',
    'admin-announcement-level-error': 'Critical',
    'admin-announcement-post-btn': 'Post',
    'admin-announcement-empty': 'Message cannot be empty.',
    'admin-announcement-success': 'Announcement posted.',
    'admin-announcement-fail': 'Failed to post announcement.',
    'admin-no-data': 'No data available.',
    'admin-view-chat': 'View Chat',
    'admin-chat-viewer-title': 'Chat Log',
    'admin-no-chat-history': 'No chat history for this room.',
    'admin-chat-load-fail': 'Failed to load chat log.',

    // Credits
    'credits-title': 'Credits',
    'credits-font-heading': 'Heading Font',
    'credits-font-body': 'Body Font',

    // Update Notes
    'update-notes-title': 'What\'s New in Version {version}',
    'update-notes-close': 'Close',
    'update-notes-v1.1.0': `
* **UI Redesign**: Revamped the overall layout, color scheme, corner rounding, and shadows for a more modern and polished look.
* **Enhanced Filter Functionality**: Added "Select/Deselect All" buttons to each filter group (Weapon Type, Sub, Special) for bulk actions.
* **Improved Usability**: Made it visually clearer that controls are disabled during the roulette spin by making them semi-transparent.
* **Collapsible Filters**: Each filter group can now be collapsed to keep the screen tidy. This state is saved.
* ***Note: Saved data from previous versions has been reset due to potential compatibility issues.***
    `,
    'update-notes-v1.2.5': `
* **UI Redesign**: Overhauled the overall layout, color scheme, border radius, and shadows for a more modern and sophisticated look.
* **Enhanced Filter Functionality**: Added "Toggle All" buttons to each filter group (Class, Sub, Special) for bulk operations.
* **Improved Usability**: Visually clarified that controls are disabled during the roulette spin by making them semi-transparent.
* **Collapsible Filters**: Each filter group can now be collapsed to save screen space. The collapsed state is saved.
    `,

  }
};